### ISSUE TITLE
parameter clone_depth in build_settings does not work

### ISSUE THREAD

**Issue by SimonHeimberg** [php-censor/php-censor#106]
This is because the config is read after the repo is cloned.

When the config is read from the repo, it is not available before cloning. Therefore the config is read after cloning. This means it is not available when parameter clone_depth is read before doing the clone.

Possibilities to fix this:
* read config from db before cloning (when the config is in db)
    in this case write documentation that clone_depth works local only
* move this setting to a new project-only config (saved in db)

I recommend the 2nd solution. In this new config we could also add the path of a local repo to use as reference repositiory (git clone --reference-if-able /x/y/z/a ...) or maybe save variables/secrets/... for #14

**Comment by corpsee** [comment]
Thank you for the request and for the full description! :+1:

**Comment by SimonHeimberg** [comment]
Note: parameter `prefer_symlink` in `build_settings` for LocalRepository works because handleConfig is called before cloning (copying, or whatever).

**Comment by corpsee** [comment]
Fixed. See last comment in #87.
