### ISSUE TITLE
Result of pdepend plugin is not accessible

### ISSUE THREAD

**Issue by SimonHeimberg** [php-censor/php-censor#107]
The charts generated by pdepend plugin are not accessible by any url because they are not in public directory nor any controller handles this.
The pdepend plugin prints a link. But when visiting it, a 404 error is shown of course.

**Comment by corpsee** [comment]
I Will try to fix it. Thanks!

**Comment by corpsee** [comment]
See [PHPCI issue](https://github.com/Block8/PHPCI/pull/93)

**Comment by lakshmajim** [comment]
Hello @corpsee ,
Is there any workaround for this ?

**Comment by corpsee** [comment]
@lakshmajim Now I guess you may make `/runtime/builds` directory public in nginx/apache configuration. But it isn't good idea.

**Comment by SimonHeimberg** [comment]
I understand that Block8/PHPCI#93 mentions [the same problem](https://github.com/Block8/PHPCI/pull/93#issuecomment-355364986).
What they did is to display the images on the build page (in https://github.com/juanf/PHPCI/commit/39e9d948d2e7fc9974c9fe35a4046c81def6dd3c), but the printed url is still invalid.

**Comment by corpsee** [comment]
@SimonHeimberg Thank you for the link ( https://github.com/Block8/PHPCI/commit/39e9d948d2e7fc9974c9fe35a4046c81def6dd3c)!

I think we can solve the problem by special rout (controller/action) which will return files for pdepend (like `BuildStatusController::image` returns status image).

**Comment by vinpel** [comment]
Additionaly the documentation miss a yaml example of the plugin.

**Comment by corpsee** [comment]
This is an important note, thank you @vinpel! #143

**Comment by corpsee** [comment]
@SimonHeimberg @lakshmajim Fixed in branch `improve-pdepend`. Can you check it please?

**Comment by corpsee** [comment]
Merged into `master`. Feel free to reopen and comment.

**Comment by SimonHeimberg** [comment]
Confirm that the url shown in the log works.

What we do not have is a link pointing always to the newest generated version. (This would have been the functionality of the original shown link. But it did not work.) In case somebody would like to include the link in the readme, as the log text tells.

Should we mention that files in the artifacts directory will not be deleted when the build (or project) is deleted from php-censor?

**Comment by corpsee** [comment]
@SimonHeimberg You say reasonable things and questions. Now I know what to do next, thank you. 👍

1. Link to the latest build in each branch is needed.
2. Project artifacts directory deleting when deleted project is needed.
3. I think that it is OK because it is a static content, but may be we should make direct links more random (Some hash instead of project/build ids).

**Comment by SimonHeimberg** [comment]
Note to 3. (output files readable without login):
* This is expected for phpmd. Else it is not possible to include the generated images in an online REAMDE.
* This is maybe unexpected for code coverage of phpunit. The coverage results show the entire source code. This is no problem for FOSS projects, but for others. A warning sounds apropriate.

**Comment by corpsee** [comment]
Done.

1. Added links for the last build of branch (for PHPUnit and PDepend artifacts).
2. Application remove artifacts when removed build or project. 
3. Now names of the directories is more random.

@SimonHeimberg Can you check changes in the branch `artifacts`? Thanks!

**Comment by corpsee** [comment]
Added global application config (`config.yml`) option `php-censor.build.allow_public_artifacts` for allow/deny to generate public artifacts.

**Comment by corpsee** [comment]
Now in `master` branch.
