### ISSUE TITLE
file runtime/console.log may become very big

### ISSUE THREAD

**Issue by SimonHeimberg** [php-censor/php-censor#108]
Possibilities to fix this:
* Mention this file in the doc and recommend something like logrotate
* Keep the file at limited size automatically, maybe by using RotatingFileHandler from monolog

**Comment by corpsee** [comment]
I Will think about how to fix it. Thanks!

**Comment by corpsee** [comment]
I added option to the main application config (`app/config.yml`) for daily `console.log` rotate. Example:
```yaml
php-censor:
  ...
  log:
    rotate: true
    max_files: 30
```

By default option `rotate` is `false` and option `max_files` is `0` (unlimite if rotate is turn on).

@SimonHeimberg Can you check log rotation in `feature-log-rotate` branch?

**Comment by SimonHeimberg** [comment]
I have updated to this branch and have added the config. Today logging goes into file `.../runtime/console-2017-08-30.log`, the old `console.log` remains in place.

Looks good to me. Anything else I should check?

**Comment by corpsee** [comment]
@SimonHeimberg Thanks!
