### ISSUE TITLE
Survey: Project config in project repository removing

### ISSUE THREAD

**Issue by corpsee** [php-censor/php-censor#109]
@vinpel, @ketchoop, @valeriitropin, @JoolsMcFly, @ss-gxp, @bochkovprivate, @StudioMaX, @SimonHeimberg, @LEXASOFT Does anyone use a project config in the project repostory (`.phpci` or `.php-censor`)? How is it important for you in self-hosted CI system?

What do you think about removing it from PHP Censor in the near future?

This would combine the configurations (project config + environment config) and fundamentally solve the issue #106 and similar issues.

Thanks!

**Comment by ketchoop** [comment]
@corpsee And it'll look like CIs from 2010. I think this is actual feature nowadays(because of microservices) and it's hard to manage a lot of configuration of many projects in CI, IMO.

**Comment by valeriitropin** [comment]
@corpsee I use it. It helps me to define specific branch settings so I would leave this feature.

**Comment by valeriitropin** [comment]
And one more thing: not every developer should have admin access to php censor so config in the repo gives possibility for each developer in the team to configure CI for a project. I think it's important.

**Comment by corpsee** [comment]
@ketchoop @valeriitropin Thanks. These are serious reasons to leave the config.

**Comment by bochkovprivate** [comment]
We use it. And it is nice to have config in repository because:
a) we can than have different project config for different branches;
b) we can track config changes using git/mecurial that is very useful.

**Comment by ss-gxp** [comment]
We do not use.
Of course it would be useful to track configs changes, but it's also convenient to keep them in one place (for example, if you change a large number of configs).

Perhaps should make the configuration flexible as possible, for example, to get config(s) from a separate repository?

**Comment by corpsee** [comment]
@bochkovprivate @ss-gxp Thanks. I will think about more flexible project configurations.

**Comment by vinpel** [comment]
We us it, same as bochkovprivate, really usefull to have git history

**Comment by corpsee** [comment]
@vinpel Thanks.

**Comment by SimonHeimberg** [comment]
We do not (yet?) use it.
We run several tests on one project (security daily on master, phpunit with coverage during the night only when branch had changes, general checks on commit, ...). So we could include the main config, but not the others.

To have a history for the config is very useful. I currently have them in a repo, and copy paste into the ui. Simplifying would be nice.

Btw, is `.php-censor` a security risk, because every user allowed to push can execute arbitrary code with `shell`?

**Comment by corpsee** [comment]
> Btw, is .php-censor a security risk, because every user allowed to push can execute arbitrary code with shell?

@SimonHeimberg Thanks. Every who have access to the repository, yes. Access rights is the huge separate issue.
