### ISSUE TITLE
Survey: What version of PHP are you using with PHP Censor?

### ISSUE THREAD

**Issue by corpsee** [php-censor/php-censor#117]
What version of PHP are you using with PHP Censor? Somebody use PHP5.6?

@vinpel, @ketchoop, @valeriitropin, @JoolsMcFly, @ss-gxp, @bochkovprivate, @StudioMaX, @SimonHeimberg, @LEXASOFT, @borNfreee, @ptejada What about your environment?

Thanks!

**Comment by StudioMaX** [comment]
I'm still using 5.6 because there are another PHP projects at the same server which cannot be updated to 7.0.

**Comment by corpsee** [comment]
Thank you @StudioMaX!

**Comment by ss-gxp** [comment]
We use 5.6, for the same reason - the update is not yet possible.

**Comment by vinpel** [comment]
php version 7.1 (php-censor is used in a rkt pod so i have the liberty of php version)

**Comment by corpsee** [comment]
Thanks @vinpel @ss-gxp!

P.S.: I don't want to drop PHP 5.6 support, but I want to know statistics.

**Comment by SimonHeimberg** [comment]
php 7.0.22

**Comment by corpsee** [comment]
Thank you @SimonHeimberg!

**Comment by mattgorle** [comment]
Currently, PHP 7.1.11 on our CI server.  I'm investigating PHP 7.2 on my dev machine with a view to rolling it out to the CI server and beyond.

**Comment by corpsee** [comment]
@mattgorle Thank you! :+1: Create issue if there are problems with PHP 7.2.
