### ISSUE TITLE
Dashboard is slow on a large number of projects

### ISSUE THREAD

**Issue by ss-gxp** [php-censor/php-censor#120]
I now have slightly more than 50 projects and have to wait long time before the dashboard will open.
The reason is:
* large number of sql requests.
* large number of ajax requests (each of the displayed projects is updated with a separate query!)

My opinion is that with a large number of projects, it is not necessary to display them all. It is enough to display projects in which the last build is not successful and those that are currently being built.

What do you think about it?

I have branch in which this is implemented (this is draft, but for me it gives an acceptable result now):
https://github.com/ss-gxp/php-censor/commits/speedup-dashboard

**Comment by corpsee** [comment]
The problem is clear to me and I like the idea of speed up dashboard. I'll think about it and will look at your branch and write again what I think with more details. Thank you @ ss-gxp.

**Comment by corpsee** [comment]
[`id` -> {{id}} for postgres](https://github.com/ss-gxp/php-censor/commit/f489a5353cb2f37510afb31d094917d5fad5e9e1#commitcomment-24373393)

**Comment by corpsee** [comment]
@ss-gxp First, I looked your branch and I like what you did! :beer:

Secondly, I think that we can't simply replace current dashboard widget with all projects to your 'build errors' widget. But I see the flexible solution:
1. Leave the current widget (`all_projects`) and add your widget too (`build_errors`).
2. Add to the PHP Censor common configuration option to customize the display of widgets on the dashboard. Like:
```yaml
php-censor:
  dashboard_widgets:
    - build_errors
    - all_projects
```

And you can use something like that for your case:
```yaml
php-censor:
  dashboard_widgets:
    - build_errors
```

What are you think about it?

**Comment by ss-gxp** [comment]
Good idea.
It takes time to separate the widgets, but that's right.
Also I think the build history (the last 10) also needs to be turned into widget.

**Comment by corpsee** [comment]
@ss-gxp Timeline as a widget is good idea too) Thanks!

**Comment by corpsee** [comment]
Done (#131).
