### ISSUE TITLE
Create command for create build periodical

### ISSUE THREAD

**Issue by corpsee** [php-censor/php-censor#125]
Create command for create build periodical (if no new builds from webhook).

**Comment by Vincentv92** [comment]
Currently I'am looking into this issue, but I have difficulty with understanding what you mean. Because there is already a php command to create a build from the console.

With periodical, can you give an example?

**Comment by corpsee** [comment]
Hi @Vincentv92. I mean command should check where was last build and if it was too long time ago (for example 30 days ago) than command create new build. it is necessary for check project dependencies, for example, pepiodicaly if no weebhook builds.

**Comment by Vincentv92** [comment]
Ah okay, now I understand. That makes sense, I will work on this.

**Comment by corpsee** [comment]
Great news. Thank you @Vincentv92! :+1:

**Comment by Vincentv92** [comment]
Please see #126 for the first try, I would like to hear your feedback!

**Comment by corpsee** [comment]
Thanks @Vincentv92!
