### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by lscortesc** [php-censor/php-censor#127]
### Installation Failed
When i was try to install PHP Censor i've got this problem:

![issuephpcensormigrations](https://user-images.githubusercontent.com/6760803/31839161-8f1dc436-b5a5-11e7-91c3-f1a231137d93.png)

```php
[PDOException]
SQLSTATE[HY000]: General error: 1553 Cannot drop index 'project_id': needed in a foreign key constraint
```

### How to reproduce

1. Clone repo
2. Go to project path
3. Run 
```shell
./bin/console php-censor:install
```

**Comment by corpsee** [comment]
Thanks @lscortesc!
