### ISSUE TITLE
Empty website

### ISSUE THREAD

**Issue by DanielRuf** [php-censor/php-censor#135]
The website of php-censor contains nothing. Is this intended?

**Comment by corpsee** [comment]
Website is in progress... You can read [documentation](https://github.com/php-censor/php-censor/tree/master/docs/en) now instead of website for info.

@DanielRuf Thank you for reminding!

**Comment by DanielRuf** [comment]
Ok, thanks for the information.

**Comment by SimonHeimberg** [comment]
currently http://php-censor.info redirects to https://github.com/php-censor/php-censor.
Redirecting to https://github.com/php-censor/php-censor#readme would be nicer

**Comment by corpsee** [comment]
@SimonHeimberg It has sense. Thank you!
