### ISSUE TITLE
PHP 7.2 unpack user from session

### ISSUE THREAD

**Issue by oln0ry** [php-censor/php-censor#136]
PHP Censor's dashboard

## Actual behavior

HTTP 500 error and record in error log.

FastCGI sent in stderr: "PHP message: PHP Fatal error:  PHPCensor\Helper\Lang::init(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;PHPCensor\Model\User&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /opt/projects/php-censor.local/src/PHPCensor/Helper/Lang.php on line 143" while reading response header from upstream, client: 127.0.0.1, server: php-censor.anochat.ru, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "php-censor.example.ru"

## Steps to reproduce

Setup in automatic mode with bin/console and open host at web browser

## Environment

Ubuntu 16.04 PHP 7.2.0 MariaDb 10.2.11

**Comment by corpsee** [comment]
I will try to test it soon. Thanks, @oln0ry!

**Comment by oln0ry** [comment]
@corpsee it can be fixed by
`if ((!is_object($user) || get_class($user) == '__PHP_Incomplete_Class') && gettype($user) == 'object') {
            $user = unserialize(serialize($_SESSION['php-censor-user']));
        }`

**Comment by corpsee** [comment]
Thank you, very useful comment :+1:
