### ISSUE TITLE
phpcs plugin ignores "path" setting

### ISSUE THREAD

**Issue by leewillis77** [php-censor/php-censor#153]
## Expected behavior

phpcs only run on the path defined in the .php-censor.yml file, e.g. 

```
test:
    php_code_sniffer:
        path: "app"
```

phpcs should only check and report errors on files under the "app" folder. This config looks correct according to [the docs](https://github.com/php-censor/php-censor/blob/master/docs/en/plugins/php_code_sniffer.md), and works on PHPCI.

## Actual behavior

The path is ignored, and phpcs is run against the full project. Debug output below:
```
RUNNING PLUGIN: PHP Code Sniffer (Stage: Test)
Plugin options: {"standard":"\/phpcs.xml","path":"app","allowed_warnings":10,"allowed_errors":5}
Looking for binary: phpcs
Found in ./vendor/bin (local): phpcs
Args: ["\/var\/www\/phpcensor\/runtime\/builds\/5_24c5e\/vendor\/bin\/phpcs --report=json %s %s %s %s %s \"%s\" %s %s %s"," --standard=\/var\/www\/phpcensor\/runtime\/builds\/5_24c5e\/\/phpcs.xml"," --extensions=php"," --ignore=vendor","","","\/var\/www\/phpcensor\/runtime\/builds\/5_24c5e\/","","",""]
Command: ./vendor/bin/phpcs --report=json  --standard=.//phpcs.xml  --extensions=php  --ignore=vendor   "./"   
Execution status: 2
PLUGIN: SUCCESS
```

Note the final "Command" output which shows that phpcs is running against `./`, not `app`.

## Steps to reproduce

- Limit the path in .php-censor.yml, make sure a file outside that path has errors that will be flagged. 
- Run build.
- Confirm that errors in files outside of the path are reported

## Environment

PHP: 7.1.13
PHP-Censor: 0.20.0

**Comment by leewillis77** [comment]
Also confirmed that this still exists with 0.21.0

**Comment by corpsee** [comment]
@leewillis77 Thanks! Bug confirmed.

**Comment by AlexisFinn** [comment]
Hi, I saw this too and corrected it locally. It's real easy:
in src/PHPCensor/Plugin/PhpCodeSniffer.php
Anywhere in the  __construct function add the following
```php        
if (isset($options['path'])) {
    $this->path = $options['path'];
}
```
That's it, all the rest of the code is there just waiting to use the setting, it was just never set in the constructor.

**Comment by corpsee** [comment]
@AlexisFinn Good research, thanks!

**Comment by corpsee** [comment]
@AlexisFinn Can you make pull request with your local changes please?

**Comment by AlexisFinn** [comment]
Ok, done.

Sorry for the somewhat messy process, this is the first time I do this.

**Comment by corpsee** [comment]
@AlexisFinn Don't worry, it is Ok. Congratulations on your first request!

**Comment by leewillis77** [comment]
Thanks both 👍
