### ISSUE TITLE
SSH-Key Strength

### ISSUE THREAD

**Issue by KuGelFaaaNg** [php-censor/php-censor#154]
## Expected behavior
It should be possible to setup a SSH-Key strength.
In Gitlab I use at least 4096 Bit Key's.

## Actual behavior

*A generated SSH-Key has a strength of 2048 B.*

## Steps to reproduce

*Add Project.*

*src/PHPCensor/Helper/SshKey.php*

```php
$output = @shell_exec('ssh-keygen -t rsa -b 2048 -f '.$keyFile.' -N "" -C "deploy@php-censor"');
```

**Comment by corpsee** [comment]
@KuGelFaaaNg Thank you for the idea!

**Comment by KuGelFaaaNg** [comment]
@corpsee With pleasure. I could implement it. But I think you are a little faster.

**Comment by KuGelFaaaNg** [comment]
Please make it also possible to change the key description with used domain. 
Something like *deploy.php-censor@domain.tld* 😄

**Comment by corpsee** [comment]
@KuGelFaaaNg Ok :smile: I may add parameter to global application config `app/config.yml`. Is it normal solution for you?

About description - Ok.

I will try to fix it at this week.

**Comment by KuGelFaaaNg** [comment]
Sure this is a good solution for me. Thank you!

**Comment by corpsee** [comment]
@KuGelFaaaNg Done. Can you check issue in the branch `ssh-strength`?

**Comment by KuGelFaaaNg** [comment]
@corpsee I did. Works fine. Thank you 👍

**Comment by corpsee** [comment]
Thanks!
