### ISSUE TITLE
Use Web Notifications API in front-end to notify active users of build changes

### ISSUE THREAD

**Issue by prezire** [php-censor/php-censor#156]
This request is taken from an old request in the original PHPCI issues thread: https://github.com/Block8/PHPCI/issues/255.

Please see quoted descriptions below from the original thread.

--------------------------------------------------------------------------------------------------------------------

> This would be nice for build notifications, just like the IRC plugin. Some documentation is available at developer.apple.com.
> 
> Right now I think we just need to configure the message and the icon (success, failure). Any other ideas?

--------------------------------------------------------------------------------------------------------------------

> This is very good idea, something i have missed in other CIs.
> 
> Maybe a wrapper like this https://github.com/alexgibson/notify.js would make it easier to build this?
> That will make it work for other browsers, such as Chrome, Safari & Firefox.
> 
> Problem I can see is that this is a frontend plugin more or less. which can be hard to make work if the users is not active on the website. Is it any way to make that work?

**Comment by corpsee** [comment]
Hi, @prezire. Thank you for the good idea! Pull requests are welcome :smiling_imp:

**Comment by prezire** [comment]
I can create the UI and integrate the Push Notification part. Do you guys have suggestions where to put the push-notif-server.php? In needs to be executed as "php push-notif-server.php" but I'm having difficulty integrating it, even as a Command. Inputs would helpful.

**Comment by corpsee** [comment]
I guess you should write (and use) daemon (command wich works permanent) for push server. For example see [how works](https://github.com/php-censor/php-censor/blob/master/src/Command/WorkerCommand.php) ([and setups](https://github.com/php-censor/php-censor/blob/master/docs/en/workers/worker.md)) worker command.

**Comment by prezire** [comment]
Nice. I was thinking of something similar. I'll take a look. Thanks for pointing this out!

**Comment by prezire** [comment]
I found out I might have taken this to a wrong direction with ZMQ, which isn't needed for now. The original request was mostly talking about the UI side. I'll do a Pull Request for it and then file another issue request relating to ZMQ.

**Comment by corpsee** [comment]
@prezire First, thank you for your work! I suggest to keep the pull request opened and work on it. Without backend part this changes is useless.

**Comment by prezire** [comment]
@corpsee No worries. A back-end was involved. But the feature is mostly related to front-end, which gives users a notification popup no matter what page they are viewing, or even when the browser window is not focused or minimized.

**Comment by corpsee** [comment]
@prezire Ok.

**Comment by prezire** [comment]
Thanks for the tips @corpsee . By the way, there's a codecove issue similar to the phpunit pull request. Is this a blocker to our pull requests not approved?

**Comment by corpsee** [comment]
No, codecove mostly for information. It is not blocker in common case.

**Comment by prezire** [comment]
Cool. Thanks for clearing it up.

**Comment by corpsee** [comment]
I added option `php-censor.notifications.enabled` (`true/false`) for enable/disable notifications. By default the option is `false`.

**Comment by corpsee** [comment]
@prezire Any news about backend part?

**Comment by prezire** [comment]
@corpsee I'm still super preoccupied as of the moment. I'll get back to speed once I'm free. For the meantime, please see the Apr 5 reply.

**Comment by corpsee** [comment]
@prezire OK, thanks.

**Comment by corpsee** [comment]
@prezire I removed your code with web notification frontend part because it is useless without backend. If you want to to implement back-end part in the future, please create pull request with full feature (front-end + backend).

I will keep issue open, may be someone else want to implement feature.

**Comment by prezire** [comment]
Hi @corpsee It's using a UI notification. See the title. The back-end feature is just an enhancement using sockets. Otherwise, it still works.

**Comment by corpsee** [comment]
It is working bad without backend and send same notifications again and again after each page reload.

**Comment by prezire** [comment]
It's currently, it's riding the existing methods. I just added a new notification UI. I think it needs a singleton or session manager of some sort. Thanks for the info.

**Comment by corpsee** [comment]
You are welcome!
