### ISSUE TITLE
Support GitHub Enterprise

### ISSUE THREAD

**Issue by ysakai3** [php-censor/php-censor#163]
## Expected behavior

Support for GitHub Enterprise would be interesting as a new addition, as it isn't currently supported.

## Steps to reproduce

I was able to link it by changing the URL of GitHub.com to my GitHub Enterprise Instance's hostname at
/var/www/php-censor.local/src/PHPCensor/Model/Build/GithubBuild.php

## Environment

* PHP Censor version
* Operating System
* PHP version
* MySQL/PostgreSQL version

**Comment by corpsee** [comment]
@ysakai3 Thank you! Good suggestion. I wll try to do this later.

**Comment by corpsee** [comment]
I added support for GitHub Enterprise in `master` branch.

@ysakai3 Can you check the feature please? You should update your PHP Censor to fresh `master`, edit your project and set to `reference` form field full repository URI (Like `git@example.com:owner/repository.git`).

**Comment by ysakai3** [comment]
@corpsee Which repository type should I choose at `Where is your project hosted` ? (e.g. GitHub, Bitbucket..) 
![1](https://user-images.githubusercontent.com/32917290/38597679-06ef7470-3d94-11e8-81ad-4cdc5500d385.PNG)

**Comment by corpsee** [comment]
@ysakai3 GitHub.

**Comment by ysakai3** [comment]
@corpsee I can confirm that I am able to have it build via webhook coming from GitHub Enterprise. But since the project is configured as GitHub.com, when I click on the branch or commit reference in the project, it jumps to the url with github.com as the hostname.

**Comment by corpsee** [comment]
@ysakai3 I guess you don't change field "Repository Name / URL (Remote) or Path (Local)" to full repository path: `root/clon` to `git@your-repository.com:root/clon.git`.

If domain isn't exist it use "github.com" by default.

**Comment by corpsee** [comment]
@ysakai3 Any news?

**Comment by ysakai3** [comment]
@corpsee thanks for checking in. I haven't had the chance to go in detail yet, but I will let you know next week how it goes!

**Comment by corpsee** [comment]
@ysakai3 OK, thank you!

**Comment by ysakai3** [comment]
@corpsee 
### I'm able to have the project build with push event webhook:
![build](https://user-images.githubusercontent.com/32917290/39104525-17a07db2-46ec-11e8-9d41-7170e7497e45.PNG)

### Project settings:
![project_settings](https://user-images.githubusercontent.com/32917290/39104498-f9495654-46eb-11e8-8222-a4e0babc9753.PNG)

### Clicking the master branch in the red box above should go to the repository, but the result is:
![result](https://user-images.githubusercontent.com/32917290/39104704-7c513170-46ec-11e8-944c-d2bd50766247.PNG)

**Comment by corpsee** [comment]
@ysakai3 Thanks for the detailed explanation. Now problem confirmed by me (I guess problem in IP instead of domain name). I will fix it soon.

**Comment by corpsee** [comment]
@ysakai3 

1. Right format of SSH URI is: `git@172.25.186.4:root/clon.git` instead of `git@172.25.186.4/root/clon.git` as I know.

2. Could you give me output of `git rev-parse HEAD` command on your PHP Censor installation?

**Comment by ysakai3** [comment]
@corpsee 

> Right format of SSH URI is: git@172.25.186.4:root/clon.git instead of git@172.25.186.4/root/clon.git as I know.

I used git@172.25.186.4:root/clon.git instead and can confirm it is working now!

> Could you give me output of git rev-parse HEAD command on your PHP Censor installation?

$ git rev-parse HEAD
0a022390edc9f7f996a568d122df3167a276f720

**Comment by corpsee** [comment]
> $ git rev-parse HEAD
> 0a02239

You should checkout on fresh `master`. I pushed some fixes after commit 0a02239 for parsing GitHub URI. (I guess after update your HEAD `git@172.25.186.4/root/clon.git` will work fine too).

**Comment by corpsee** [comment]
@ysakai3 Can I close issue?

**Comment by ysakai3** [comment]
@corpsee 

I updated the repo and can confirm using `git@172.25.186.4/root/clon.git` works as well.

Yes, you can close this issue now, thanks!
