### ISSUE TITLE
Initial build folder not automatically created

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [php-censor/php-censor#165]
## Expected behavior

Build to start and private key file created inside initial build folder

## Actual behavior
```
Exception: Warning: file_put_contents(php-censor/runtime/builds/1/1_bdb12f16.key): failed to open stream: No such file or directory in php-censor/src/Model/Build.php line 478

BUILD FAILED

Removing Build.
```
## Steps to reproduce

Create a new build and run it.

## Environment

* master
* Arch Linux
* 7.2
* MariaDB

**Comment by Caffe1neAdd1ct** [comment]
Manually creating the build number folder inside php-censor/runtime/builds e.g `php-censor/runtime/builds/1/` then runs the build successfully.

**Comment by corpsee** [comment]
@Caffe1neAdd1ct I guess your worker/cron-user doesn't have rights to write to the web-user's directory.

**Comment by Caffe1neAdd1ct** [comment]
I'm running both the webserver (php inbuilt webserver) and the worker both on my local user at the moment so there should be no permission issues. Cloning works fine after the directory is created so i don't think it's permissions related (i may be wrong will investigate if time permits).

**Comment by corpsee** [comment]
Oh... I understand where problem: `php-censor/runtime/builds/1/1_bdb12f16.key` (from your log). But normal path should be: `php-censor/runtime/builds/1/1_bdb12f16/<key>.key`.

Thank you for the report!

**Comment by corpsee** [comment]
@Caffe1neAdd1ct Fixed. Can you check it please?

**Comment by Caffe1neAdd1ct** [comment]
Did a quick pull:

```
git pull origin master
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 9 (delta 7), reused 8 (delta 7), pack-reused 0
Unpacking objects: 100% (9/9), done.
From https://github.com/php-censor/php-censor
 * branch              master     -> FETCH_HEAD
   0286880c..7747193c  master     -> origin/master
Updating 0286880c..7747193c
Fast-forward
 src/Model/Build.php          | 4 ++--
 src/Model/Build/GitBuild.php | 2 +-
 src/Model/Build/HgBuild.php  | 2 +-
 3 files changed, 4 insertions(+), 4 deletions(-)
```

Restarted the webserver and worker
Deleted and recreated the project

Still getting folder issues:

```
Exception: Warning: file_put_contents(./temp.key): failed to open stream: No such file or directory in php-censor/src/Model/Build.php line 478

BUILD FAILED

Removing Build.
```

Doing a `watch -n 1 ls -l`  on the php-censor/runtime/builds/ directory i'm still not getting a folder created.

A quick `mkdir 3` (3 being the project) before solved it, however now i'm still getting:

```
Exception: Warning: file_put_contents(./temp.key): failed to open stream: No such file or directory in php-censor/src/Model/Build.php line 478
```

**Comment by Caffe1neAdd1ct** [comment]
Printing out the full file path from the `writeSshKey` method gives me:

```
php-censor/runtime/builds/3/33_d27647d2/temp.key
```

i've made sure the `3` directory exists manually (still an issue) however this can't be put inside `33_d27647d2` as this doesn't appear to be created at this point either?

**Comment by corpsee** [comment]
@Caffe1neAdd1ct Can you check `master` branch again please? I fixed problem by moving keys to system temp directory until build directory doesn't exist.

**Comment by Caffe1neAdd1ct** [comment]
@corpsee Perfect! All working :+1:

**Comment by corpsee** [comment]
Thanks @Caffe1neAdd1ct!
