### ISSUE TITLE
[PHP 7.2] PHP Docblock Checker fails

### ISSUE THREAD

**Issue by ismaail** [php-censor/php-censor#170]
### Expected behavior

```
RUNNING PLUGIN: PHP Docblock Checker (Stage: Test)
PLUGIN: FAILED (ALLOWED)
```

### Actual behavior

```
RUNNING PLUGIN: PHP Docblock Checker (Stage: Test)
Exception: Warning: count(): Parameter must be an array or an object that implements Countable in /home/docker/src/Plugin/PhpDocblockChecker.php line 137
PLUGIN: FAILED (ALLOWED)
```

### Steps to reproduce
The cause is the change of [count()](http://php.net/manual/en/function.count.php#refsect1-function.count-changelog) function in PHP 7.2

### Environment

* PHP Censor version: cb735ccf
* OS: Docker container: fpm-alpine
* PHP version: 7.2
* MySQL: 7.5

**Comment by corpsee** [comment]
@ismaail I fixed PhpDockblockChecker plugin in the `master` branch. Can you test this again please (on the fresh `master`)?

**Comment by ismaail** [comment]
now PHP Docblock Checker successfully passes:

```
RUNNING PLUGIN: PHP Docblock Checker (Stage: Test)
PLUGIN: SUCCESS
```

Thanks a lot
