### ISSUE TITLE
Blank page after new setup

### ISSUE THREAD

**Issue by dfranco** [php-censor/php-censor#180]
## Expected behavior

At least the login form or any web app error message

## Actual behavior

I get only a blank page
Apache error log shows nothing.
Any way to enable debug mode ?

## Steps to reproduce

Installed php-censor using Apache2 with MySQL db back-end.
I've followed instructions from Readme.md

## Environment
Ubuntu 16.04
Apache/2.4.18
MySQL server 5.7.22
PHP 7.0.30
PHP Censor 0.22.0

Any help would be welcome.

Best regards

**Comment by corpsee** [comment]
@dfranco 

1. Is PHP error reporting enabled (`error_reporting(E_ALL)`)?
2. I guess It may be problem with session starting (Check rights of the PHP session directory, check then directory exists etc.).

**Comment by dfranco** [comment]
Hi @corpsee 

Thanks for your feedback.

1. Yes, this is already the case.
2. PHP setting session.save_path is set and the folder does exist

**Comment by corpsee** [comment]
@dfranco Can you try to start PHP Censor on PHP build-in server without Apache2 (Something like: `php -S localhost:8000 -t ./public`)?

**Comment by dfranco** [comment]
@corpsee 

1. Here it is
``# php -S localhost:8000 -t ./public
``PHP 7.0.30-0ubuntu0.16.04.1 Development Server started at Fri May 25 12:46:16 2018
``Listening on http://localhost:8000
``Document root is /var/www/php-censor/public
``Press Ctrl-C to quit.

``[Fri May 25 12:46:20 2018] 127.0.0.1:33490 [302]: /

It look's like I get a 302 error code

2. Yes, mod_rewrite is enabled

**Comment by corpsee** [comment]
@dfranco Thanks. About your first point (build-in server): You should change `php-censor.url` param in `app/config.yml` too (from your local address to `localhost:8000`).

**Comment by dfranco** [comment]
Hi @corpsee 
I've updated the config.yml file and now I'm able to get the login page using this command
`` $ wget http://localhost:8000
But it doesn't work if rollback to the fqdn using my web browser.
What could be wrong ?
Thanks for your help

**Comment by corpsee** [comment]
I'm not clear, are you using FQDN with build-in server too or with Apache2?

May be problem with browser's redirects. Are you using Chrome or something else? Can you check in another browser?

**Comment by dfranco** [comment]
Hi @corpsee 
I'm using Apache2, no built-in server
I'm doing my tests with Firefox by the way

Thanks your help

**Comment by corpsee** [comment]
I guess problem with how Apache2 (or system) configured. It is difficult to understand what is going wrong remotely(

**Comment by dfranco** [comment]
@corpsee 

Fair enough
I'll try to fix my setup and get back to you if I find a fix

Thanks for your help anyway

**Comment by corpsee** [comment]
Not at all) I am keeping issue opened until you fix your installation, may be it is a bug.

**Comment by dfranco** [comment]
@corpsee 
My mistake, I've found the issue (typo in Apache vhost configuration).

Thanks for your help
