### ISSUE TITLE
How to test Javascript and CSS errors in php-censor

### ISSUE THREAD

**Issue by Shar-2018** [php-censor/php-censor#181]
## Expected behavior

When I run 'Squiz' standards I expect JavaScript errors in my .js files to be detected.

## Actual behavior

*no errors detected in .js files*

## Steps to reproduce

*In the file .php-censor.yml
 Set the 
php_code_sniffer:
standard= Squiz

Then commit  the .js files and php files  and build.
Result:
Errors in .js files are not detected.
Errors in .php files are detected

## Environment

* PHP Censor version - 0.22.0
* Operating System - CentOS 7.x
* PHP version - PHP 7.2
* MySQL/PostgreSQL version -MariaDB Server 10.1.33

**Comment by corpsee** [comment]
@Shar-2018 According to [PHP_CodeSniffer documentation](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#generic-coding-standard-configuration-options), you should set the paths to remote CSS/JS utilities (CSSLint, JSLint etc.).

But now PHP Censor PHPCodeSniffer plugin doesn't allow to set options like `--config-set jslint_path <path>`.

Pull request for improve PHPCodeSniffer plugin for JS are wellcome;)
