### ISSUE TITLE
Codeception : Exception: String could not be parsed as XML without test error => plugin failed

### ISSUE THREAD

**Issue by vinpel** [php-censor/php-censor#182]
## Expected behavior

codeception without fail sould not cause FAILED plugin because XML generated by Codeception

## Actual behavior

![image](https://user-images.githubusercontent.com/1699839/40547863-574c03d6-6033-11e8-9fcc-287e2e1dd58d.png)

## Steps to reproduce
During the codeception testphp print some formated lines.

The output is formatted with ascii color, the "esc" char render the XML invalid.

A sample of the xml :

```XML
 <testcase name="testOrdonnateurActifSansClefNiParam" class="corporate\modules\ordonnateur\TachesLancePasTest" file="/data/htdocs/phpci/runtime/builds/4/2328_da038af9/vendor/oisehabitat/modules-ordonnateur/tests/unit/TachesLancePasTest.php" assertions="7" time="0.201335">
      <system-out>[0m[32;1mListe des [0m[0m[31;1mtâches[0m[0m[32;1m :
------------------[0m
[0m[1;33mId[0m   [0m[1;33mHeure demarrage[0m  [0m[1;33mUnikey[0m              [0m[1;33mGroupe[0m    [0m[1;33mNextExec[0m       [0m[1;33mStatus[0m         [0m[1;33mAgent[0m                    [0m[1;33mClass[0m                                             [0m[1;33mArguments[0m                                         

</system-out>
    </testcase>
```

## Environment

* PHP Censor version: @master
* Operating System 4.14.42-coreos
* PHP version PHP 7.1.16 (cli) (built: Apr  5 2018 17:26:10) ( NTS )
* MySQL/PostgreSQL non relevant

**Comment by corpsee** [comment]
@vinpel Thank you for the detailed report. I will try to fix the issue soon.

**Comment by corpsee** [comment]
@vinpel Can you attach file with invalid Codeception XML without your secret data for tests?

**Comment by corpsee** [comment]
@vinpel Can you check your case in branch `codeception-xml` please?

**Comment by corpsee** [comment]
@vinpel Thank you!

**Comment by corpsee** [comment]
@vinpel Can you check branch `codeception-xml` again please?

**Comment by corpsee** [comment]
@vinpel Can you check one more time?

**Comment by vinpel** [comment]
```bash
Time: 3.84 minutes, Memory: 768.00MB
OK, but incomplete, skipped, or risky tests!
Tests: 413, Assertions: 2134, Skipped: 17.
run with `-v` to get more info about skipped or incomplete tests
- XML report generated in file://./console/runtime/logs/report.xml
PLUGIN: SUCCESS
```
all good !!!

**Comment by corpsee** [comment]
@vinpel Thanks! Awesome)
