### ISSUE TITLE
weebhook : "error":"Content type not supported" 

### ISSUE THREAD

**Issue by vinpel** [php-censor/php-censor#185]
## Expected behavior

Accessing webHook in gogs :

https://myPhpCensor.loc/webhook/gogs/2

## Actual behavior
reponse : 
```json
{"status":"failed","error":"Content type not supported."}
```
Log : 
```bash
PHP Notice:  Undefined index: CONTENT_TYPE in /data/htdocs/phpci/src/Controller/WebhookController.php on line 608
```

## Steps to reproduce

accessing them in a navigateur

## Environment

* PHP Censor master
* Operating System Linux
* PHP version version PHP 7.1.16 (cli) (built: Apr  5 2018 17:26:10) ( NTS )
* MySQL/PostgreSQL version n/a

**Comment by corpsee** [comment]
@vinpel Thanks. I will fix it.

**Comment by corpsee** [comment]
Can you give me your request example without secret data please (`Content-Type` header and request body)?

**Comment by corpsee** [comment]
@vinpel Can you check fix in the branch `gogs-content-type`?

**Comment by vinpel** [comment]
seem good : {"status":"ignored","message":"Unusable payload."}

**Comment by corpsee** [comment]
@vinpel :+1:
