### ISSUE TITLE
Running Custom PhpUnit Binary

### ISSUE THREAD

**Issue by kiler129** [php-censor/php-censor#187]
For Symfony-based projects `phpunit-bridge` is often used, which requires running `bin/phpunit`. Is there a way to configure this in `php-censor`?
If not I think we should add such option.

## Environment

* PHP Censor version
`0.22.0`

* Operating System
`Debian 9.4`

* PHP version
`PHP 7.2.5-1+0~20180505045740.21+stretch~1.gbpca2fa6`

* MySQL/PostgreSQL version
`10.0.28-MariaDB-1~jessie`

**Comment by corpsee** [comment]
@kiler129 Thank you. It makes sense.

**Comment by kiler129** [comment]
@corpsee If you don't mind I can look during the weekend and submit a PR.

**Comment by corpsee** [comment]
@kiler129 It would be great! PR are always welcome :)

**Comment by ismaail** [comment]
Hi, 

I'm using **Symfony 4** project that uses **symfony/phpunit-bridge**, 

the PHPUnit tests passes without a problem,

phpunit configuration:

```
test:
  php_unit:
    config: "phpunit.xml.dist"
```

#### Build log
```
RUNNING PLUGIN: PHP Unit (Stage: Test)
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
Warning:       Deprecated JSON test listener used
Testing Project Test Suite
..                                                                  2 / 2 (100%)
Time: 677 ms, Memory: 34.25MB
OK (2 tests, 2 assertions)
```

#### Environment

- PHPCensor version:  0.23.0 (eef73d8)
- OS: Docker alpine-fpm
- PHP: 7.2.8
- DB: MySQL 7.5

**Comment by SimonHeimberg** [comment]
My work-around: create link ./vendor/bin/phpunit pointing to my desired binary (by a shell plugin in the config)

**Comment by corpsee** [comment]
@SimonHeimberg Thank you! I guess this issue may be closed.
