### ISSUE TITLE
Undocumented fail timeout

### ISSUE THREAD

**Issue by bochkovprivate** [php-censor/php-censor#190]
I have a long set of phpunit tests in my setup. 
One day I’ve faced a problem: after normally running about 30 minutes something happens and build corrupts: on each and every command it starts geting error message like 
`shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory`.
Generally it looks like a project build directory has been deleted by someone.

It took me a couple of days to discover the cause. In Command/RunCommand.php the is a non documented build timeout:
`$timeout = Config::getInstance()->get(‘php-censor.build.failed_after’, 1800)`

So by default after running 30 minutes php-censor gracefully drops build directory (without telling anything to webapp console), keeps calm and continues to build in the non-existent directory.

I’d suggest the following:
1. Document this setting in app/config.yml
2. Interrupt the build process and distinctively complain to webapp colsole in case of timeout.

**Comment by corpsee** [comment]
Thanks!

**Comment by corpsee** [comment]
I removed option `php-censor.build.failed_after` in the branch `worker`. I think if build is working for the long time we should solve this problem manually.

@bochkovprivate Can you test `worker` branch please?

**Comment by corpsee** [comment]
Now in `master` branch.
