### ISSUE TITLE
Choose error types in Quality Trend

### ISSUE THREAD

**Issue by caouecs** [php-censor/php-censor#196]
## Expected behavior

In Quality Trend panel, we have a list of errors with the number of recurrences.

I would like to define this list directly in _.php-censor.yml_ or in _app/config.yml_

## Actual behavior

The list is defined in public/assets/js/build-plugins/warnings.js lines 5 and 30.

**Comment by corpsee** [comment]
@caouecs Thanks. Good idea!

**Comment by corpsee** [comment]
Now Quality Trend panel shows only plugins with errors count > 0. I close issue.
