### ISSUE TITLE
HowTo - Run against different PHP Versions

### ISSUE THREAD

**Issue by andres-montanez** [php-censor/php-censor#199]
Hi, I was reading the documentation but I couldn't find an answer.
Is it possible to run builds against different PHP versions?
I saw there are a couple of issues opened about the same topic, which suggest having different workers to take care of the different versions.

Is there any workaround or documentation for achieving this?

Much appreciated!

**Comment by corpsee** [comment]
Hi, @andres-montanez.

It is imposible to build project with different PHP versions (Excluding radical variant with several full PHP Censor installations) now.

If we want to get this feature (I write about simple implementation with several PHP interpretators on host system without containers like do TravisCI) we need to do several changes:

1. All workers are equivalent and any build runs on any free worker now. We need ability to start workers with tags and ability to send build to the specific worker (or pull of workers) based on tag.

2. We need to rework project configuration to add list of tags (PHP versions in this specific case) for build several builds by one push/start. We already have similar feature '[environments](https://github.com/php-censor/php-censor/blob/master/docs/en/environments.md)' but environments don't need specific workers. It would be perfect if we refactor environments and merge environments and worker tags.

I have plans to implement this feature, but probably not very soon (May be after the 1.0 release).

And pull requests are welcome! :)

**Comment by andres-montanez** [comment]
Thanks man!

**Comment by corpsee** [comment]
Duplicate. See #46.
