### ISSUE TITLE
Access current build-stage in plugin execution

### ISSUE THREAD

**Issue by ht-bs** [php-censor/php-censor#200]
I would like to get the current build-stage (setup, test, ...) in my plugin.
I did not see a way to access it, did I miss something or is that not implemented? I do not care if this would be possible through a getter, or parameter via constructor or the execute method.

**Comment by corpsee** [comment]
@ht-bs You can only get full project config and parse it manualy (`$config = $this->builder->getConfig();`).

But I can add method `getCurrentStage()` to `Builder` class when I will have time. It is not a problem.

**Comment by corpsee** [comment]
Done in the `master` branch.

You can call in the plugin code `$this->builder->getCurrentStage()` for getting current build stage.
