### ISSUE TITLE
Add title and description by build

### ISSUE THREAD

**Issue by caouecs** [php-censor/php-censor#201]
For each build, we could have the possibility to define a title and/or a description. This would identify in the graph the different builds if its are important milestones.

**Comment by corpsee** [comment]
@caouecs It is the interested idea, thanks. Where would you want to set title (New UI with build editing or something another)?

**Comment by caouecs** [comment]
I think like Github with the description of repository

https://screenshots.firefox.com/T5B0NCEHpvFWEHW5/172.16.129.103

**Comment by corpsee** [comment]
Ок. But who and how will **set** description? Many builds creates by external services (GitHub, BitBucket etc.) and the services doesn't send description. I see one real way and It is setting description manually by user, but we don't have any page for editing build information now.
