### ISSUE TITLE
How to tell php censor the name of git branch which should be used for build?

### ISSUE THREAD

**Issue by mirdic** [php-censor/php-censor#206]
## Expected behavior

When commited to different branch than default (master), php-censor should use this branch (for example branch called test) for build. Instead php-censor uses always default branch - master.

## Steps to reproduce

![project](https://user-images.githubusercontent.com/458238/43360809-1ca85dc4-92bf-11e8-97c7-0871e286b933.png)

## Environment

* PHP Censor version 0.22
* Ubuntu 16
* 7.2
* MySQL 5.6

**Comment by mirdic** [comment]
Found it! You have to put branch name in web hook as parameter 
`https://example.com/webhook/git/1?branch=test`

**Comment by corpsee** [comment]
:+1:
