### ISSUE TITLE
The "wipe" option from the Copy Build plugin doesn't work

### ISSUE THREAD

**Issue by jwmwalrus** [php-censor/php-censor#207]
Hi.

When setting the `complete.copy_build.wipe` option to `true`, no wipe is performed before the build is copied.

It's certainly not a deal breaker, but storage can become an issue pretty quickly when using the Copy Build plugin.

## Environment

* PHP Censor version: 0.23.0-1-geef73d8e
* Operating System: Debian GNU/Linux 9.5 (stretch)
* PHP version: 7.2.7-1+0\~20180622080745.23+stretch~1.gbpfd8e2e
* MySQL/PostgreSQL version: 15.1 Distrib 10.1.26-MariaDB

**Comment by corpsee** [comment]
@jwmwalrus Thanks.

**Comment by corpsee** [comment]
@jwmwalrus Can you test the problem on `local-build` branch please? But you can know that I change LocalBuild logic little bit.

**Comment by jwmwalrus** [comment]
Hi.

I can confirm that when in the `local-build` branch, the contents of the target directory are removed when `wipe: true` is used (and the copied build is no longer in a subdirectory of the target directory).

**Comment by corpsee** [comment]
Thank you! I merged `local-build` to `master`.
