### ISSUE TITLE
Some commits trigger git error "fatal: reference is not a tree: ##########"

### ISSUE THREAD

**Issue by ndom91** [php-censor/php-censor#208]
## Expected behavior

Clones git repo, run setup bash command, run tests, and then run setup bash scripts. See .php-censor.yml below.

## Actual behavior

Normally, and on about 80% of commits / Webhook (push) and 100% of manual builds it works flawlessly. However, on some commits, and it doesnt seem to have anythign to do with the contents, sometimes it just a spelling correction in the README.md sometimes its more complex commits, it gets triggered via the webhook (push) and fails directly to clone the git repo. 

After this error occurs, I can trigger a manual build and that will run directly without problem.

See screenshot of `runtime/console.log`  

![image](https://user-images.githubusercontent.com/7415984/44464691-bbce7e00-a61b-11e8-9194-409013829564.png)
## .php-censor.yml contents:

```bash
setup:
  shell:
    - "%BUILD_PATH%/install.sh"
test:
  technical_debt:
    allowed_errors: -1
    ignore: 
      - "library/Zend/"
      - "library/PHPExcel/"
  php_loc:
    directory: "application"
  lint:
    directories:
      - "application/"
      - "public/"
complete:
  email:
    default_mailto_address: yo@yo.yo
  shell:
    - |
        if [ -d '/var/www/html/ntdb-%BRANCH%' ]; then
            rm -r /var/www/html/ntdb-%BRANCH% 
        fi
    - "cp -r %BUILD_PATH%/ /var/www/html/ntdb-%BRANCH%"
    - |
        # sed for setting up cli.ini
        sed -i 's/params.host = "xxxxxxxx"/params.host = "localhost"/g' /var/www/html/ntdb-%BRANCH%/application/configs/cli.ini
        sed -i 's/params.dbname = "d0172461"/params.dbname = "newtelco"/g' /var/www/html/ntdb-%BRANCH%/application/configs/cli.ini
        sed -i 's/params.username = "d0172461"/params.username = "newtelco"/g' /var/www/html/ntdb-%BRANCH%/application/configs/cli.ini
        sed -i 's/params.password = "xxxxxxxxxx"/params.password = "N3wt3lco"/g' /var/www/html/ntdb-%BRANCH%/application/configs/cli.ini
        
        # sed for setting up application.ini
        sed -i 's/db.host = "xxxxxxxx"/db.host = "localhost"/g' /var/www/html/ntdb-%BRANCH%/application/configs/application.ini
        sed -i 's/db.dbname = "d0172461"/db.dbname = "newtelco"/g' /var/www/html/ntdb-%BRANCH%/application/configs/application.ini
        sed -i 's/db.username = "d0172461"/db.username = "newtelco"/g' /var/www/html/ntdb-%BRANCH%/application/configs/application.ini
        sed -i 's/db.password = "xxxxxxxxx"/db.password = "N3wt3lco"/g' /var/www/html/ntdb-%BRANCH%/application/configs/application.ini
        
        # old way of simply copying the config file from the live vhost to the new test env - this did not allow us to change the db from prod to test though
        #cp /var/www/html/ntdb-git/application/configs/application.ini /var/www/html/ntdb-%BRANCH%/application/configs/application.ini
        
    - "chown -R nginx: /var/www/html/ntdb-%BRANCH%"

```

## Environment

* PHP Censor version - 0.23.0
* Operating System - CentOS 6.10
* PHP version - 7.0.31
* MySQL/PostgreSQL version - mysql 5.5.60

**Comment by corpsee** [comment]
@ndom91 Thank you for the detailed report.

**Comment by corpsee** [comment]
@ndom91 At the moment I am not having free time to debug your problem, sorry. If you can debug problem and get more details It will help me in the future.

I will try to fix it when I have opportunity.

You can also try to test your problem on another versions (0.22 for example) and may be we can understand where bug in code.

Thank you.

**Comment by corpsee** [comment]
@ndom91 Are you using `build_settings.clone_depth` option in your build config (`.php-censor.yml`)? It would be the problem if `clone_depth` is too small.

**Comment by ndom91** [comment]
@corpsee unfortunately no, I am not using the `clone_depth` setting. My whole .php-censor.yml is included above.

**Comment by corpsee** [comment]
@ndom91 OK, thank you. I will look for another reason.

**Comment by ndom91** [comment]
I have noticed this only happened when it pulled and tried to build multiple commits at once. It probably errored then when trying to create the same build dir multiple times simutaenously. 

I created a new project with the same details and it seems to work flawlessly now. Therefore I will close this.

Thanks for takign the time to look into it, however!
