### ISSUE TITLE
How To Remove Old Builds?

### ISSUE THREAD

**Issue by mikebronner** [php-censor/php-censor#209]
Sorry if I missed it somewhere (I checked the documentation and searched the repo for issues): how do you keep only a certain number of builds? The problem is that it keeps filling up the server.

Thanks! :)

**Comment by jwmwalrus** [comment]
Hi.

At the moment, there's also the issue of the *copied build* and the *artifacts*:
* Once you delete the build from the web view, the log is not available anymore, and therefore the link to the *artifacts* is lost.
* In my case, the *copied build* is only useful for failed builds, so I tried the wipe option (see #207 )  to avoid filling up the server ---but with two consecutive failures and (functional) `wipe: true`, I'd only get a copy of the last build, which could be totally unrelated to the previous failure.

It would be nice to have a tab (e.g., **Artifacts**) next to the **Information** one, showing the links to the generated artifacts, and the option/buttons to delete their contents.  Said tab could also include a button to delete the copied build, if any.

**Comment by corpsee** [comment]
@jwmwalrus Can you create new issue for 'artifactory tab' please? It is good idea, thanks. :+1:

P.S.: By the way about your first point: when you delete build, artifacts for build are also deleted. And link become useless.

**Comment by corpsee** [comment]
@mikebronner I added buttons 'Delete all builds' and 'Delete old builds' to the project page (Available for admins).

New option `php_censor.builds.keep_builds` from main application config (`app/config.yml`) define how many latest builds should kept (By default: latest 100).

Changes already in the `master` branch but before using this feature make DB backup (on the off-chance).
