### ISSUE TITLE
With incomplete tests, status is reported as "Failed" while the build is in progress

### ISSUE THREAD

**Issue by jwmwalrus** [php-censor/php-censor#210]
Hi.

When a PHPUnit test suite contains incomplete tests, the status in the web view is reported as "Failed" while the build is in progress.

At the end of the build, the status is the right one (i.e., "Success", unless any of the non-incomplete tests fails), so the issue is a minor one.

* PHP Censor version: 0.23.0-2-gdd36471f
* Operating System: Debian GNU/Linux 9.5 (stretch)
* PHP version: PHP 7.2.8-1+0\~20180725124257.2+stretch~1.gbp571e56
* MySQL/PostgreSQL version: mysql Ver 15.1 Distrib 10.1.26-MariaDB

Edit:
I forgot to mention that, although the build is still in progress, the "Failed" status is reported by email.  And later, once the build is finished and successful, a second email is sent.

**Comment by corpsee** [comment]
@jwmwalrus Thanks!

**Comment by corpsee** [comment]
@jwmwalrus I can not reproduce case from the issue. Could you check again on fresh `master` branch please? Is it still happening? Thanks.

**Comment by jwmwalrus** [comment]
Due to submodule-related issues, I am unable to go beyond the setup step when trying  to rebuild a successful commit from September 3rd.

Nevertheless, the issue was that when the PHPUnit test suite contains a test like this one: 
```php
<?php

namespace Tests\SomeVendor\SomeBundle\Controller;

use Liip\FunctionalTestBundle\Test\WebTestCase;

class SomeTest extends WebTestCase
{
    public function testDoSomething()
    {
        $this->markTestIncomplete(
            'TODO: implement'
        );
    }
}
```

Then the web view shows the build as "failed" right after running the incomplete test, although the test step continues ---and at the end of the build, the status is "success".


Right now, my test suite migrated from PHPUnit to Codeception, and an equivalent incomplete test would be:

```php
<?php

namespace Tests\SomeVendor\Config\Controller;

class MyCest
{
    public function skipTest(\AcceptanceTester $I, $scenario)
    {
        $scenario->skip('Unknown');
    }
}
```

But with Codeception there are no "partially failed" builds (even though Codeception still uses PHPUnit).

Not sure if the issue was related to PHPUnit sending info about incomplete and skipped tests to the _stderr_ stream.

Anyway, I suppose this issue can be closed for now.

**Comment by corpsee** [comment]
@jwmwalrus Thank you for the explanation! I will try to fix incomplete tests anyway.
