### ISSUE TITLE
When running Phinx during setup, it gets the -vvv option somehow

### ISSUE THREAD

**Issue by jwmwalrus** [php-censor/php-censor#212]
Hi.

I have a `setup.php` script, which takes care of ensuring all the necessary conditions are set before running the tests.

One of the things the setup script does is running (Phinx) migrations.  The command executed is `passthru('./bin/phinx migrate -e test', $retval);`, but when run from a PHP Censor's build it gets way too verbose ---it's somehow getting the -vvv flag, which means the log is getting a lot of unnecessary information.

Both Phinx and PHP Censor are built upon Symfony's Console component, so maybe verbose setting is shared?

## Environment

* PHP Censor version: 0.23.0-6-gb9580adc
* Operating System: Debian GNU/Linux 9.5 (stretch)
* PHP version: PHP 7.2.8-1+0\~20180725124257.2+stretch~1.gbp571e56
* MySQL/PostgreSQL version: mysql  Ver 15.1 Distrib 10.1.26-MariaDB

**Comment by corpsee** [comment]
@jwmwalrus Thank you for the report!

**Comment by garas** [comment]
Symfony [verbosity](https://symfony.com/doc/current/console/verbosity.html) is controlled by `-vvv` or `SHELL_VERBOSITY` environment variable.

If you start PHP Censor with `-vvv`, Symfony will [put](https://github.com/symfony/console/blob/8c544db578c749f12e43fd22ca2486976d60d85f/Application.php#L872) `SHELL_VERBOSITY=3` environment variable and subprocesses will see this value.

> The `-q` and `-v` options still have more precedence over the value of `SHELL_VERBOSITY`.

Pass one of them to subprocess.

**Comment by corpsee** [comment]
Thank you @garas! Very detailed and useful answer :+1:
@jwmwalrus I think I may close the issue.

**Comment by jwmwalrus** [comment]
I just checked that by prefixing the invocation of Phinx with `SHELL_VERBOSITY=0`, the verbose output goes away.  So, thanks a lot for the suggestion.

Although, I think It would be good for PHP Censor not to influence the output of commands run through the shell plugin ---i.e., PHP Censor should take care of setting that environment variable to zero when starting those subprocesses.

**Comment by corpsee** [comment]
@jwmwalrus It would be good, but I don't have any idea how fix it without full isolation of build (containers for builds). If you have another way, PRs are welcome :)

**Comment by corpsee** [comment]
Related to #247.

**Comment by corpsee** [comment]
Fixed in #269. Fix will be released with version `1.1.0`.
