### ISSUE TITLE
cloning to gitlab instance on custom ssh port

### ISSUE THREAD

**Issue by ndom91** [php-censor/php-censor#213]
## Expected behavior

Clone successful, working dir created

## Actual behavior

Project Gitlab URL: `git@git.xyz.de:2424/abc/xyz.git`

```bash
Initialized empty Git repository in ./.git/
ssh: connect to host git.newtelco.de port 22: Connection refused
fatal: The remote end hung up unexpectedly
```

According to my googling, many have suggested creating a `~/.ssh/config` file to create an ssh shortcut, I did this, however php-censor does not seem to recognize this when executing its ssh git pull. I thought it might have been because it is being executed as the nginx user, so I put this config file also in the home dir of nginx (`/var/lib/nginx/.ssh/config`), but that wasn't recognized either. Contents of my .ssh/config file are:

```bash
Host git.xyz.de
        hostname git.xyz.de
        port 2424
        User git
        PubKeyAuthentication yes
        IdentityFile /home/xyz/.ssh/id_xyz
```

Then I tried to insert the port into the project URL, but that still wasn't recognized / applied either. It still always said `ssh: connect to host git.newtelco.de port 22: Connection refused`. I tried the following URL variations:

* `git@git.xyz.de:2424/abc/xyz.git`
* `git@git.xyz.de:2424:abc/xyz.git`
* `git@git.xyz.de:abc/xyz.git:2424`

Has anyone successfully pulled from a custom ssh port? This only applies to self-hosted Gitlab instances as well I guess since Github and Bitbucket and the like aren't going to be changing their SSH ports.. haha

**EDIT:** 
For example, when using `git@git.xyz.de:2424/abc/xyz.git`
 
We get the following output (scroll all the way to the right to see full attempted URL): 
```bash
Command: export GIT_SSH="/tmp/sh_FSkiLt" && cd .. && git clone --recursive  -b "master" "git@git.xyz.de:2424/abc/xyz.git" "./"
Initialized empty Git repository in ./.git/
ssh: connect to host git.xyz.de port 22: Connection refused
fatal: The remote end hung up unexpectedly
```

**EDIT2:**
When sshing in normally, my ~/.ssh/config works:

```bash
$(13:12)-(80Kb)$ ssh git@git.xyz.de
PTY allocation request failed on channel 0
Welcome to GitLab, @root!
Connection to git.xyz.de closed.
```

## Environment

* PHP Censor version - 0.23.0
* nginx version - 1.10.2
* Operating System - CentOS 6.10
* PHP version - 7.0.31
* MySQL/PostgreSQL version - mysql 5.5.60

**Comment by ndom91** [comment]
So in case anyone was having a similar issue, I found a temporary workaround (not changing the port back! Haha).

So I grepped around a bit and found where the ssh statement is being executed. That is apparently in `./src/Model/Build.php`.

Here at line `557` you can replace this: 

```
ssh {$sshFlags} -o IdentityFile={$keyFile} $*
```

With this: 
```
ssh -p [port number] {$sshFlags} -o IdentityFile={$keyFile} $*

i.e.

ssh -p 2424 {$sshFlags} -o IdentityFile={$keyFile} $*
```

**Comment by corpsee** [comment]
@ndom91 Thank you for the useful workaround! :+1: Can you test your case on branch `ssh-port`?

**Comment by ndom91** [comment]
@corpsee sure, you just want me to modify the Build.php file on that branch and test it again? Or have you built in another way to modify the ssh port on that branch?

**Comment by corpsee** [comment]
@ndom91 In `ssh-port` branch port takes from repository URL. Just checkout branch and check your case without manual modifications.

**Comment by ndom91** [comment]
@corpsee okay, how does it expect the repo URL to be formatted though?

**Comment by ndom91** [comment]
Okay so I tried the URLs:

* git@git.xyz.de:2424/abc/xyz.git
* git@git.xyz.de:2424:abc/xyz.git

And they both did not work. They didn't complain about hanging up from port 22 however. The port part seemed to work. It now complained about not finding my project, so the URL after the Port somehow was misformatted im assuming..

**Comment by garas** [comment]
`[user@]host.xz:path/to/repo.git/` doesn't support custom port.
Use `ssh://[user@]host.xz[:port]/path/to/repo.git/` syntax.

See https://git-scm.com/docs/git-push#_git_urls_a_id_urls_a

**Comment by ndom91** [comment]
Unfortunately `ssh://git@git.xyz.de:2424/abc/xyz.git` also resulted in:

```
GitLab: The project you were looking for could not be found.
fatal: The remote end hung up unexpectedly
```

I am on the `ssh-port` branch btw, just so we're clear haha

**Comment by corpsee** [comment]
@ndom91 Can you select from DB table `project` your project and show me field `access_information`? You can replace your personal secret information by examples. Thanks.

**Comment by ndom91** [comment]
So the whole `access_information` field looks like this (with person info obviously replaced):

```
  3 | Title  | {"user":"git","domain":"git.xyz.de","port":"2424","reference":"abc\/xyz","origin":"ssh:\/\/git@git.xyz.de:2424\/abc\/xyz.git\/"} 
```

**Comment by ndom91** [comment]
@corpsee tried your newest commit changes.. still "project not found"

**Comment by garas** [comment]
You connect to Gitlab successfully now, but receive `GitLab: The project you were looking for could not be found.`

Do you use `ssh://git@git.xyz.de:2424/abc/xyz.git/` with slash in the end? The `origin` in your `access_information` has it.

Github doesn't allow slash in the end with `ERROR: Repository not found.`

Probably same with Gitlab.

**Comment by corpsee** [comment]
@ndom91 Did you restart worker after checkout?

**Comment by corpsee** [comment]
@ndom91 No, cronjob doesn't need restart. It is strange... Can you get and post content of temp SSH script (from `/tmp/sh_ns2aso`)?

**Comment by corpsee** [comment]
@garas May be you are have any ideas?

**Comment by ndom91** [comment]
@corpsee unfortunately the `/tmp/sh_ns2aso` dir and any other temp build dirs are not there. Either they never got  created or are deleted right away..

Did this commit allow you to pull from different SSH Ports? How exactly is your URL formatted in the Project Config?

Thanks for the help so far!

**Comment by corpsee** [comment]
@ndom91 Yes, alternative port is existing. Any of your URLs (`ssh://...`, 'git@...') are parsing correctly and port is existing in DB and then I don't khow what went wrong...  (Personaly, I don't use GitLab and non-default port and I have problem with testing your case).

**Comment by corpsee** [comment]
@ndom91 New idea for workaround: Can you put ssh key to `~/.ssh` with your domain in `~/.ssh/config` and delete ssh key from project settings (It should be empty textarea)? Than start new build.

**Comment by ndom91** [comment]
@corpsee Unfortunately then got `fatal: No path specified. See 'man git-pull' for valid url syntax` - it didnt even have the path in the debug output so I'm assuming it wasn't even able to connect

**Comment by ndom91** [comment]
@corpsee I think I will just stick with the manual workaround for now - its simply entering `-P 2424` everytime I git pull a new update. Not so bad.. haha

**Comment by garas** [comment]
Last script has `git clone` with `git@git.xyz.de:2424/abc/xyz.git`:
 * path `2424/abc/xyz.git`, that's why project not found
* there is no port, so either git connected to port 22, or git used config from `.ssh/config`

What script is generated when you use `ssh://` and with `.ssh/config` removed? What is result of script?

**Comment by ndom91** [comment]
I had been using `ssh://` in front of the project URL the entire time, it always shows up in the debug output without `ssh://`. I had the `.ssh/config` in place the whole time, so maybe it grabbed the port from there and then wasn't able to find the project because it used the path, `2424/abc/xyz.git`, like you said. 

I will try it again without the config file there whenever I get home in a little.

**Comment by garas** [comment]
Now I see the reason:

https://github.com/php-censor/php-censor/blob/b9580adc5216739c19d8ddccdaf3e012f3cbdaf7/src/Model/Build/GitlabBuild.php#L61-L65

Url is always generated as `user@host.xz:path/to/repo.git`

@corpsee Can you always add `ssh://` for Gitlab?. Same other Build classes

**Comment by corpsee** [comment]
I updated branch `ssh-port`.

@ndom91 Can you test branch `ssh-port` again?
@garas Great work! Thank you. :+1:

**Comment by ndom91** [comment]
@corpsee @garas great work guys, it worked! It kept `ssh://` in the URL in the debug output too. Thanks for the great work!

I used the following syntax for my Project URL: `ssh://git@git.xyz.de:2424/abc/xyz.git`

**Comment by corpsee** [comment]
I merged fix into `master` branch.
