### ISSUE TITLE
Local build doesn't copy files so build fails.

### ISSUE THREAD

**Issue by Musiksammler** [php-censor/php-censor#223]
Hello!

I've setup phpcensor manually in a docker container. It runs and I've setup a project hosted in local path.

My docker-compose.yml looks like this:

    phpcensor:
      ...
      volumes:
        ...
        - ../web:/var/www/html/project

So in /var/www/html/project lies my webproject with the subfolders "src", "tests" and files like "phpunit.xml" and so on. The directory is mapped correctly, I can list files and directories there in the docker container.

In the project settings I've set the path in the field "Repository Name / URL (Remote) or Path (Local)" to

    /var/www/html/project/

As far as I understand the process, when starting a build phpcensor copies all files to "runtime/builds/...". The process creates a subfolder for that build, but the filecopy doesn't work. The directory remains empty, the build fails and the subfolder gets removed immediately. So all build-steps in the .php-censor.yml don't work. Here an excerpt from the log:

    Command: mkdir -p "/var/www/html/web/php-censor/runtime/builds/1/15_11f8d36e" && cp -Rf "/var/www/html/project" "./"
    Execution status: 0
    Working copy created: ./

    RUNNING PLUGIN: Composer (Stage: Setup)
    Plugin options: {"action":"install"}
    Looking for binary: composer
    Found in  (system): composer
    Args: ["\/usr\/local\/bin\/composer --no-ansi --no-interaction  --working-dir=\"%s\" %s","\/var\/www\/html\/web\/php-censor\/runtime\/builds\/1\/15_11f8d36e\/","install"]
    Command: /usr/local/bin/composer --no-ansi --no-interaction  --working-dir="./" install
    Do not run Composer as root/super user! See https://getcomposer.org/root for details
    Composer could not find a composer.json file in /var/www/html/web/php-censor/runtime/builds/1/15_11f8d36e

Any suggestions what might be wrong?

**Comment by Musiksammler** [comment]
Okay, found the issue. I just did the "composer create-project" step during installation, believing that this will install the most current version of the tool. But instead it just installed the latest release version where this bug wasn't fixed.

Can be closed.

**Comment by corpsee** [comment]
@Musiksammler Thank you for the explanation! I will release version 0.24.0 soon for this case. :+1:

**Comment by corpsee** [comment]
P. S.: For info: If you want to install by Composer exact version or latest `master` branch you should use `<version>` argument of `create-project` like: `composer create-project php-censor/php-censor php-censor.local dev-master`.

**Comment by corpsee** [comment]
Is related to #207.

**Comment by corpsee** [comment]
Version [0.24.0](https://github.com/php-censor/php-censor/releases/tag/0.24.0) has been released.
