### ISSUE TITLE
Repository URL modified

### ISSUE THREAD

**Issue by klodoma** [php-censor/php-censor#227]
I am using a local gitlab setup. I setup the url like in the attached picture. 
![screenshot_205](https://user-images.githubusercontent.com/944350/47845350-0eb77500-ddc5-11e8-95b3-c06e2b2c744e.png)

When running a build the URL gets modified (ssh) is cut off
![screenshot_206](https://user-images.githubusercontent.com/944350/47845376-2262db80-ddc5-11e8-985d-78b08bacb718.png)

The only way to get this working is to set the repository hosting to "git", but then the webhook url is not displayed anymore. 

## Environment

* PHP Censor v0.23.0
* Operating System Ubuntu 16 LTS
* PHP version 7.1.*
* MySQL/PostgreSQL version Mysql

**Comment by garas** [comment]
Issue fixed in https://github.com/php-censor/php-censor/issues/213.

Upgrade to latest `master` until there is new release.

**Comment by corpsee** [comment]
@garas Thanks!
@klodoma

**Comment by corpsee** [comment]
@klodoma Yes, PHP Censor modify URI for clone (URI depend on SSH keys). May be I will change logic in the future, but now it should work fine on fresh `master`.

@garas Thanks!

**Comment by corpsee** [comment]
Version [0.24.0](https://github.com/php-censor/php-censor/releases/tag/0.24.0) has been released.

**Comment by klodoma** [comment]
Great! Thank you!
