### ISSUE TITLE
Authenticating composer dependencies with private repos

### ISSUE THREAD

**Issue by benr77** [php-censor/php-censor#231]
## Expected behavior

Install dependencies from private repos when doing composer install

## Actual behavior

Build fails, presumably because it cannot connect to the private repo

I can configure the private repo as a PHPCensor project, save the public key against it, and it will build ok on its own.

## Steps to reproduce

Composer.json
```
"repositories": [
		{
			"type": "vcs",
			"url":  "git@bitbucket.org:foo/somedependency.git"
		}
	],
```
When doing composer install this fails.

In the docker set up, I have created an auth.json with Bitbucket oauth credentials (as a volume of the worker container) but this is not working.

I have seen this note in the docs but it doesn't seem to help me
https://github.com/php-censor/php-censor/blob/master/docs/en/plugins/composer.md#warning

## Environment

* 0.24
* Docker
* 7.2
* MySQL

**Comment by benr77** [comment]
Sorry I forgot to add the error that I get!

`Failed: [RuntimeException] Failed to execute git clone --no-checkout 'git@bitbucket.org:foo/somedependency.git' './vendor/foo/somedependency' && cd './vendor/foo/somedependency' && git remote add composer 'git@bitbucket.org:foo/somedependency.git' && git fetch composer`

**Comment by corpsee** [comment]
@benr77 For use private git repository by SSH protocol you should have SSH keys in the user home directory (I guess `root` user for docker container).

` auth.json` is about basic HTTP auth for repositories with type `composer` (private Satis installation for example).
