### ISSUE TITLE
Dashboard message says build has never been successful

### ISSUE THREAD

**Issue by benr77** [php-censor/php-censor#232]
## Expected behavior

Dashboard message should say 

`1 out of the last 5 builds failed. The last successful build was 2018-11-27 14:52:40.`

## Actual behavior

Dashboard message actually says the project has never been built successfully, despite at the same time reporting at least some of the last n builds have succeeded etc

`1 out of the last 5 builds failed. This project has never built successfully.`

## Environment

* PHP Censor 0.24
* Docker
* PHP version 7.1 (web)
* MySQL

**Comment by corpsee** [comment]
@benr77 Thanks!

**Comment by benr77** [comment]
I can't reproduce this now. I think it was on an older project which has been deleted.

I'll close this for now and re-open it if I see the issue again. Thanks
