### ISSUE TITLE
Docblock checker repeats class name in error message

### ISSUE THREAD

**Issue by benr77** [php-censor/php-censor#234]
## Expected behavior

In the error message for docblock checker violations, I expect to see the class and method name - e.g.

`MessagingBundle\Util\EmailMessage::getSubject @return missing.`

## Actual behavior

I see the class/method name twice:

`MessagingBundle\Util\EmailMessage::getSubject::MessagingBundle\Util\EmailMessage::getSubject @return missing.`

## Steps to reproduce

Any error encountered by the docblock checker

## Environment

* PHP Censor version 0.24
* Docker
* 7.2
* MySQL

**Comment by corpsee** [comment]
@benr77 Thank you for the report!

**Comment by corpsee** [comment]
Fixed in `master` branch. @benr77 Can you check please?

**Comment by benr77** [comment]
Confirmed fixed

**Comment by corpsee** [comment]
Thanks! :+1:
