### ISSUE TITLE
Docblock checker does not support nullable type-hints

### ISSUE THREAD

**Issue by benr77** [php-censor/php-censor#235]
## Expected behavior

Nullable type-hints should not throw a dockblock error when the docblock does match the type-hint

## Actual behavior

With a method such as:

```
/**
 * @param string          $key
 * @param \Exception|null $previous
 */
public function __construct(string $key, ?\Exception $previous = null)
{

}
```
This results in the following docblock checker error

`App\Exception\SettingInvalidKeyException::__construct @param $previous(Exception|null) does not match method signature (Exception)`

In fact, the dockblock DOES match the method signature, but the docblock-checker seems unaware of the `?` prefix which marks the type-hint as nullable

## Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*

## Environment

* PHP Censor 0.24
* Operating System Docker
* PHP 7.2
* MySQL

**Comment by corpsee** [comment]
@benr77 Thanks.

**Comment by corpsee** [comment]
@benr77 Fixed in the `master` branch. Can you now check your case please (With `composer install` execution)?

**Comment by corpsee** [comment]
@benr77 :+1:
