### ISSUE TITLE
CopyBuild plugin does not copy hidden files

### ISSUE THREAD

**Issue by benr77** [php-censor/php-censor#242]
## Expected behavior

The CopyBuild plugin should copy all project files.

## Actual behavior

The CopyBuild plugin does not copy hidden files.

For example, in my project root I have a `.mage.yml` config file for deployment, but if the CopyBuild plugin is used, it does not copy this file.

## Steps to reproduce

Set up the CopyBuild plugin and run it on a project with a hidden file in the project root. See that the hidden file is then not copied to the destination folder.

It seems this is simply because the copy command uses a `*` wildcard which does not include hidden files.

https://github.com/php-censor/php-censor/blob/dbd2dedd2de3f198ee134ecec15c6e31fe7d9f3e/src/Plugin/CopyBuild.php#L63

The command could be duplicated to copy hidden files on a second execution. Alternatively, the following syntax should work to copy hidden and visible files in a single notation (replacing the `*` with `.` as noted here https://superuser.com/a/367303)

`'mkdir -p "%s" && cp -R %s/. "%s"'`

## Environment

* PHP Censor dev-master
* Docker
* PHP 7.2
* MySQL

**Comment by corpsee** [comment]
@benr77 Thanks! Very useful information about reasons. I will fix it.

**Comment by corpsee** [comment]
@benr77 Fixed in `master` branch.

**Comment by benr77** [comment]
Confirmed fixed. Thanks for your efforts!
