### ISSUE TITLE
Remove deprecated features for version 2.0

### ISSUE THREAD

**Issue by corpsee** [php-censor/php-censor#252]
Remove deprecated features for version 2.0:

- [ ] Cronjob worker (Use worker instead).
- [ ] `phpci.yml` and `.phpci.yml` configs (Use `.php-censor.yml` instead).
- [ ] `PHPCI_*` interpolation and env variables (Use `PHP_CENSOR_*` instead).
- [ ] Deprecated plugins options.

**Comment by ketchoop** [comment]
> phpci.yml and .phpci.yml configs.

What do you mean, to remove this configs? You want to make php-censor be configured by UI? If so, I think it's not good idea, IMO...

**Comment by corpsee** [comment]
Done in `2-remove-deprecated` branch and will be released with version `2.0.0`.
