### ISSUE TITLE
GitHub project cloning bug

### ISSUE THREAD

**Issue by ptejada** [php-censor/php-censor#257]
## Expected behavior

User the GitHub URL provided in the project

## Actual behavior

The GitHub project type will always attempt to use ssh protocol even an HTTP URL is provided

## Steps to reproduce

1. Add a new project
2. Select GitHub as the project type.
3. Enter URL https://github.com/php-censor/php-censor-test.git
4. Save and trigger a project build.

![image](https://user-images.githubusercontent.com/253405/51069858-32890980-1605-11e9-942e-0c08c6a55efd.png)

**Comment by corpsee** [comment]
@ptejada Thanks!

**Comment by corpsee** [comment]
It isn't bug formaly it is a point of implementation. If you have SSH-keys then you cann't clone repository by `https` with keys.

I want to refactor this functionality but I should think about good implementation.

**Comment by ptejada** [comment]
@corpsee I see. The key is present for projects by default. Using the Git project type works as expected but you don't get the GitHub specific features like commit and branch links.

**Comment by corpsee** [comment]
@ptejada You are wrong. PHP Censor works correctly with commit/branch links and no matter what protocol is used for git clone. Just try.

**Comment by ptejada** [comment]
@corpsee 

Maybe I wasn't clear. I thought that the only way to run a build for a GitHub https URL like https://github.com/php-censor/php-censor-test.git without setting a public key was to use the "Git" project type. When you use the "Git" project type you don't get the URL links you get with GitHub project type.

![image](https://user-images.githubusercontent.com/253405/51077861-2ee39a00-167a-11e9-85a0-75f10da9c65b.png)

As mentioned before. It looks like the ssh protocol is enforced when the private key is set. The issue that I had was that private key field populated by default.
![image](https://user-images.githubusercontent.com/253405/51077909-d95bbd00-167a-11e9-9727-851b537739e3.png)

Clearing the private key field for GitHub project uses the http protocol as expected. The UI doesn't make this clear but I figure it out.
