### ISSUE TITLE
[Bug] PhpParallelLint ignores ignored directories

### ISSUE THREAD

**Issue by benr77** [php-censor/php-censor#258]
## Expected behavior

Parallel Lint plugin should respect the ignored directories

## Actual behavior

The plugin fails on errors inside ignored directories.

## Steps to reproduce

Global ignore for vendors directory is configured

```
build_settings:
    ignore:
        - bin
        - node_modules
        - var
        - vendor
```

Then PhpParallelLint plugin is configured with default settings

```
test:
    php_parallel_lint: ~
```
When running the build in debug mode, I see the command does include the required ignored directories

`Command: /var/www/app/vendor/bin/parallel-lint -e php --exclude "bin" --exclude "node_modules" --exclude "var" --exclude "vendor"`

Then the build fails with an error from inside the vendor directory - e.g. 

```
Checked 10068 files in 105.9 seconds
Syntax error found in 4 files
------------------------------------------------------------
Parse error: /vendor/codeception/codeception/tests/data/Invalid.php:2
    1| <?php
  > 2| $I do nothing here
Unexpected 'do' (T_DO)
------------------------------------------------------------
```
Also as you can see the plugin takes nearly 2 minutes to process all the code in the vendor directory, which is undesirable.

STRANGE BEHAVIOUR - I have tested the command directly in a copy of the build (via `copy_build` on failure) and when running the command directly it works ok.

## Environment

* PHP Censor version MASTER
* Operating System DOCKER / Alpine
* PHP version 7.2
* MySQL

**Comment by corpsee** [comment]
@benr77 Thanks!

**Comment by corpsee** [comment]
@benr77 Could you check your case on fresh `release-1.0` or `master` branch? I fixed bug for paths with symlinks.

**Comment by corpsee** [comment]
@benr77 I don't know :disappointed: About #261: Has it ever worked before?

**Comment by benr77** [comment]
I'll add some details to #261 directly now - but in short, yes it was working until I tried `master` today

**Comment by corpsee** [comment]
@benr77 Thanks!

**Comment by corpsee** [comment]
@benr77 Could you also check `release-1.0` branch? I guess issue with Environment plugin only in the `master` branch.

**Comment by benr77** [comment]
Ok this appears to be fixed in `master` now. Thank you

**Comment by corpsee** [comment]
@benr77 Thanks!
