### ISSUE TITLE
[Feature] Feature request  Add Bitbucket self hosted Server support

### ISSUE THREAD

**Issue by fejal** [php-censor/php-censor#260]
The support for BitBucket doesn't work with BitBucket Server when self hosted.   Would like to add this option.

*note We are working on adding that now if you would like a PR when we have it working well for us.

**Comment by corpsee** [comment]
@fejal PR would be great! Thank you.

**Comment by fejal** [comment]
@corpsee   PR submitted, cleaned up the reported errors, etc.

**Comment by corpsee** [comment]
#286

**Comment by fejal** [comment]
@corpsee   Changes requested have been pushed.
