### ISSUE TITLE
[Bug] Codeception plugin inversed test to find codeception.yml

### ISSUE THREAD

**Issue by vinpel** [php-censor/php-censor#262]
Inversed test : 
https://github.com/php-censor/php-censor/blob/4c55c6e5853eac6071157ec182fcd0a23ad2b751/src/Plugin/Codeception.php#L56-L60

if $option['config'] is empty, this code use it, you need to remove the "!"

**Comment by corpsee** [comment]
@vinpel Thank you! Fixed for branches `master`, `release-1.0` and will be released with version `1.0.3`.
