### ISSUE TITLE
[Bug] Exception: Warning: chdir(): No such file or directory (errno 2)

### ISSUE THREAD

**Issue by benr77** [php-censor/php-censor#264]
## Expected behavior

Plugin succeeds

## Actual behavior

When plugin should succeed, I get error as follows:

`Exception: Warning: chdir(): No such file or directory (errno 2) in <PHP_CENSOR_PATH>/src/Plugin/TechnicalDebt.php line 165`

If I remove this plugin, then the same error crops up with a different plugin instead:

`Exception: Warning: chdir(): No such file or directory (errno 2) in <PHP_CENSOR_PATH>/src/Plugin/PhpDocblockChecker.php line 125`

In both cases, the line in question is

`chdir($currentDir);`

So looks like the `$currentDir` variable is not being supplied.

## Environment

* PHP Censor version MASTER
* Operating System DOCKER
* PHP version 7.2
* MySQL

**Comment by corpsee** [comment]
@benr77 Could you test your case on `issue-264` branch please?

**Comment by benr77** [comment]
Confirmed fixed in `issue-264`

**Comment by corpsee** [comment]
@benr77 Thanks!

**Comment by corpsee** [comment]
Released with [1.0.4](https://github.com/php-censor/php-censor/releases/tag/1.0.4).
