### ISSUE TITLE
Standardise allowable failures/warnings/errors

### ISSUE THREAD

**Issue by benr77** [php-censor/php-censor#271]
The various different plugins all seem to have different ways of permitting errors/warnings/failures.

For example the `php_cpd` plugin's documentation does not mention any way of permitting errors or warnings. With the default configuration, any duplication found will fail the build.

In order to allow the build to succeed, it is possible to add `allow_failures` although this is not documented:
```
php_cpd:
        allow_failures: true
```
However, this plugin also implements the `ZeroConfigPluginInterface` which means you can also configure the plugin as follows to allow errors/warnings:
```
php_cpd:
        zero_config: true
```
Again, this option is not documented.

Other plugins also implement inconsistently named configuration options such as `allowed_warnings`, `allowed_errors` etc.

Can we standardise the configuration options for allowing warnings and errors, or failures across all plugins?

Is the `zero_config` option really needed? It seems a bit unclear that using this option will permit warnings and errors.

Any thoughts?

**Comment by corpsee** [comment]
@benr77 Thanks! Very useful ideas.

* Plugin options should be standardised you are right. But some plugins have errors and warnings and both options (`allowed_warnings` and `allowed_errors`).

* All options including `allow_failures` need documentation. It is truth.

* Option `zero_config` is internal and added automaticaly for projects without any configuration. You **shouldn't use  `zero_config` option in your configurations**. I think public documentation don't need to include anything about `zero_config`.

**Comment by benr77** [comment]
Is `allow_failures` an option for ALL plugins?

I'll create a pull request with some documentation improvements - adding `allow_failures` and also removing any references to `zero_config`

**Comment by corpsee** [comment]
@benr77 Yes, `allow_failures` is general option for all plugins. Thank you, PR will be very helpful!

**Comment by benr77** [comment]
Ok. Whilst I'm doing this, shall we standardise the order that the config options are listed in? Should they be alphabetical, or do we list common options first?

**Comment by corpsee** [comment]
@benr77 I think the best way is adding common options in the separated first section. Order of options inside sections is not matter for me. If you want than use alphabetical order. Thanks.

**Comment by benr77** [comment]
Ok. Can you provide a list of options that apply to all plugins?

**Comment by corpsee** [comment]
Sure. Common options: `priority_path`, `binary_path`, `binary_name`, `directory`, `ignore`, `allow_failures`.

**Comment by benr77** [comment]
Done with #273
