### ISSUE TITLE
[Feature] Allow Postgres SSL Connections

### ISSUE THREAD

**Issue by mikebronner** [php-censor/php-censor#282]
## Expected behavior
Would like to be able to use `sslmode=require` on Postgres connections to connect to cloud database providers.

However, I'm unable to get it to work with the current connection settings. I'll be happy to submit a pull request, I just haven't been able to get anything to work yet by modifying `/src/Plugin/Pgsql.php` yet.

**Clarification**
I am looking how to connect the main php-censor database to Postgres via SSL, not necessarily for running individual tests. Although that might not be a bad part B to this. (I was looking int he Pgsql plugin, thinking that perhaps php-censor used it to make connections as well.)

I have started work on this in PR #283

**Comment by corpsee** [comment]
@mikebronner Could you create draft pull request? And I will try to help when I will have free time.

**Comment by mikebronner** [comment]
@corpsee sure thing... I'll get started on it today. Thanks!
