### ISSUE TITLE
[Feature] Add support for private Bitbucket repos cloned by ssh key

### ISSUE THREAD

**Issue by EduardMalik** [php-censor/php-censor#284]
Now if using repository type bitbucket, php-censor automatically adds https://bitbucket for writed path in project. If i write git@bitbucket.org:USER_NAME/USER_REPO.git  this auto transform to https://bitbucket.org/git@bitbucket.USER_NAME/USER_REPO.git.git

If i use type git, git cloned successful, but bitbucket hook not work, because expected type for Bitbucket hook is Project::TYPE_BITBUCKET and Project::TYPE_BITBUCKET_HG, but not Project::TYPE_GIT

**Comment by corpsee** [comment]
You have empty ssh key and application forced `https://` protocol. Code for choosing protocol for clone looks like:

```php
protected function getCloneUrl() {
    $key = trim($this->getProject()->getSshPrivateKey());

    if (!empty($key)) {
        return 'git@bitbucket.org:' . $this->getProject()->getReference() . '.git';
    } else {
        return 'https://bitbucket.org/' . $this->getProject()->getReference() . '.git';
    }
}
```

As I know @bochkovprivate (may be anyone else) use private Bitbucket and it works fine. You should solve problem with your ssh keys.
