### ISSUE TITLE
[Bug] Part of Worker Documentation (config.yml keys) Completely Missing

### ISSUE THREAD

**Issue by ndom91** [php-censor/php-censor#288]
Trying to migrate from cron "worker" to legitimate beanstalkd and supervisor workers. However, the docs seem to be completely missing a crucial piece of info. What needs to be added to our config.yml.

## Actual behavior

In the docs, where it begins to tell you how to define the worker keys in your config.yml, host and queue, it says to refer to a screenshot, but then there is not image file. I checked the history of that worker.md file and there used to be links to images, but those links dont work anymore and I couldn't find the info anywhere else.

See screenshot:

![image](https://user-images.githubusercontent.com/7415984/54041441-0682a280-41c8-11e9-9c87-a5cb256da233.png)

Running `php bin/console php-censor:worker` manually results in the error message: "worker not configured, you must set host and queue in config.yml", of course.

Because of this supervisor also obviously can't execute the worker processes either.

So the question is simply, how exactly is the worker (queue and host) section of the config file supposed to be setup? Can anyone provide an example.

Thanks!

## Environment

* PHP Censor version - **1.0.6**
* Operating System - **CentOS 6**
* PHP version - **7.0.31**
* MySQL/PostgreSQL version - **14.14**

**Comment by corpsee** [comment]
@ndom91 You should add to the `config.yml` file new section `queue` like:

```yml
php-censor:
  queue:
    use_queue: true
    host:      localhost
    name:      php-censor-queue
    lifetime:  600
```

Don't close issue please I will add details to documentation soon. Thank you for the report!

**Comment by ndom91** [comment]
Thanks a lot!

**Comment by corpsee** [comment]
Done.
