### ISSUE TITLE
[Feature] Allow run only one build at a time

### ISSUE THREAD

**Issue by mirdic** [php-censor/php-censor#293]
It would be nice, to have settings for project to run only one build at a time. We are using for each build the same database, and if two or more builds run synchronously, errors appear.

**Comment by corpsee** [comment]
@mirdic I don't clearly understand your case, but:

1. If you start **only one** worker/cronjob than builds will be process one after another.
2. Database works fine with many parallel queries. May be problem in database configuration?

**Comment by mirdic** [comment]
@corpsee thanks for the quick reply!

The issue was with my settings of cron that was running `php-censor:run-builds` every minute and sometimes (if there was more than one build in queue) overlapping since my build run take approx. 70s. So i used flock to lock the cron run. https://ma.ttias.be/prevent-cronjobs-from-overlapping-in-linux/

Thanks for help and the good work on php-censor 👍
