### ISSUE TITLE
Bit Bucket Server Project URL add.

### ISSUE THREAD

**Issue by fejal** [php-censor/php-censor#296]
For our implementation for Bit Bucket Server the Repository URL for the project to access the repository is a ssh path.  This ssh path doesn't work for the links in the UI to the branches due to the url for the repo and the webbased access are different.

Would adding a field for the web url for project that is in addition to the repo url be an ok addition?

Should this appear only for the Bit Bucket Server project or for any project?

Will build it, just wanted some feedback on implementation.

![image](https://user-images.githubusercontent.com/35620647/56312553-5dac5900-611e-11e9-85d2-ee127072dcdb.png)

**Comment by corpsee** [comment]
@fejal I think we should use one common implementation for all build types. Are you see how links works in Gitlab type build? Maybe you can use `access_information` instead of raw reference like in Gitlab?

**Comment by TrxadeIT** [comment]
Working on this.

Trying to get the build hook (on pull request) to run the build with debug flag on.

This is what I put in the .php-censor.yml   file:
![image](https://user-images.githubusercontent.com/49990699/57723272-46e21f00-7656-11e9-9439-705fc68caeab.png)

But the PR generated builds never run in debug and always delete the build.
Any thing I'm doing wrong.

**Comment by corpsee** [comment]
@TrxadeIT Section `build_settings` from `.php-censor.yml` doesn't have the options `remove-builds` and `debug`. See [documentation](https://github.com/php-censor/php-censor/blob/master/docs/en/configuring_project.md#common-build-settings).

Option `remove_builds` exists in global [application congiration](https://github.com/php-censor/php-censor/blob/master/docs/en/configuring_application.md).

Option `debug` should be define when you start cronjob/worker as CLI-parameter.
