### ISSUE TITLE
Field 'branch' doesn't have a default value

### ISSUE THREAD

**Issue by kromonos** [php-censor/php-censor#310]
After moving my PHP Censor installation to a new server I get the SQL error "Field 'branch' doesn't have a default value" when I try to manually build a project.

> #0 /var/customers/webs/kromonos/phpci.kromonos.net/src/Store.php(218): PDOStatement->execute(Array)
> #1 /var/customers/webs/kromonos/phpci.kromonos.net/src/Store.php(135): PHPCensor\Store->saveByInsert(Object(PHPCensor\Model\Build), false)
> #2 /var/customers/webs/kromonos/phpci.kromonos.net/src/Service/BuildService.php(116): PHPCensor\Store->save(Object(PHPCensor\Model\Build))
> #3 /var/customers/webs/kromonos/phpci.kromonos.net/src/Controller/ProjectController.php(240): PHPCensor\Service\BuildService->createBuild(Object(PHPCensor\Model\Project), NULL, '', 'master', NULL, 'k@bka.li', NULL, 1, 1, Array)
> #4 [internal function]: PHPCensor\Controller\ProjectController->build('3')
> #5 /var/customers/webs/kromonos/phpci.kromonos.net/src/Controller.php(63): call_user_func_array(Array, Array)
> #6 /var/customers/webs/kromonos/phpci.kromonos.net/src/WebController.php(87): PHPCensor\Controller->handleAction('build', Array)
> #7 /var/customers/webs/kromonos/phpci.kromonos.net/src/Application.php(139): PHPCensor\WebController->handleAction('build', Array)
> #8 /var/customers/webs/kromonos/phpci.kromonos.net/src/Application.php(150): PHPCensor\Application->handleRequestInner()
> #9 /var/customers/webs/kromonos/phpci.kromonos.net/public/index.php(8): PHPCensor\Application->handleRequest()
> #10 {main}

I tried bin/console php-censor-migrations:migrate but doesn't help. bin/console php-censor-migrations:status shows me an interesting line:
` up  20190712152800  2019-08-15 21:43:38  2019-08-15 21:43:38  FixedBuildBranch                       ** MISSING **`

I'm on master branch from github. PHP 7.3.8 and Apache 2.4.

**Comment by corpsee** [comment]
@kromonos Thanks. I will try to fix soon.

**Comment by corpsee** [comment]
@kromonos Are you sure on latest `master` commit? Could you show your git commit hash?

**Comment by kromonos** [comment]
Yes, I'm on the latest master commit. 

> # git show
> commit d60682f7814c53be02445ed008a8659bb9e3ed19 (HEAD -> master, origin/master, origin/HEAD)
> Merge: 9adf1b1a 4c98575b
> Author: Dmitry Khomutov <poisoncorpsee@gmail.com>
> Date:   Thu Aug 8 00:32:31 2019 +0700
> 
>     Merge branch 'release-1.1'

But it's really funny. After a push into one of my repositorys, PHP Censor runs an automated build. After this, I'm able to run builds manually again 🤔

**Comment by corpsee** [comment]
@kromonos Ok. I will try to search the bug. Tell me if you will have the bug again.

**Comment by corpsee** [comment]
@kromonos Thanks!
