### ISSUE TITLE
[Feature] Hopefully it can be compatible with Windows

### ISSUE THREAD

**Issue by JuniorXcoder** [php-censor/php-censor#319]
Hopefully it can be compatible with Windows
considering we can not ignore the increasing number of Windows users

**Comment by corpsee** [comment]
@JuniorXcoder Thanks. It is a good feature, but with low priority so far.

**Comment by lugark** [comment]
Can i ask a stupid question? What does is meant exaclty being compatible with Windows? Using a Wamp-Stack? Never tested that because i use a docker-container for Windows.

**Comment by garas** [comment]
For example, make sure shell commands can run on Windows.

https://github.com/php-censor/php-censor/blob/4e0c52594e46f1700af760a35812b3e59d448732/src/Plugin/CopyBuild.php#L64

There is no `cp` on Windows.

**Comment by corpsee** [comment]
Now the best way to use PHP Censor on Windows is use VM or Docker. Previously, there was a compatibility layer for Windows, but it was difficult to maintain.

**Comment by ptejada** [comment]
With WSL becoming more popular in windows now adding support for windows or the NTFS filesystem doesn't sound like good time investment. This requests should not even be considered as a new feature.

**Comment by corpsee** [comment]
@ptejada I agree.
