### ISSUE TITLE
[Localization] Improve Portuguese (Brazil) localization (lang.pt-br.php)

### ISSUE THREAD

**Issue by corpsee** [php-censor/php-censor#348]
See [lang.pt-br.php](https://github.com/php-censor/php-censor/blob/master/src/Languages/lang.pt-br.php):

**Not present strings:** 'per_page', 'default', 'remember_me', 'environment_x', 'project_groups', 'build_now_debug', 'delete_old_builds', 'delete_all_builds', 'projects_with_build_errors', 'no_build_errors', 'failed_allowed', 'error', 'skipped', 'trace', 'default_branch_only', 'overwrite_build_config', 'environments_label', 'all', 'environment', 'build_source', 'source_unknown', 'source_manual_web', 'source_manual_console', 'source_periodical', 'source_webhook_push', 'source_webhook_pull_request_created', 'source_webhook_pull_request_updated', 'source_webhook_pull_request_approved', 'source_webhook_pull_request_merged', 'group_projects', 'project_group', 'group_count', 'group_edit', 'group_delete', 'group_add', 'group_add_edit', 'group_title', 'group_save', 'is_new', 'new', 'rebuild_now_debug', 'all_errors', 'only_new', 'only_old', 'new_errors', 'total_errors', 'classes', 'methods', 'coverage', 'phan_warnings', 'php_cs_fixer_warnings', 'php_cpd_warnings', 'php_tal_lint_warnings', 'php_tal_lint_errors', 'behat_warnings', 'sensiolabs_insight_warnings', 'technical_debt_warnings', 'merged_branches', 'suite', 'test', 'github_app_linked', 'seconds', 'stage_deploy', 'severity', 'all_plugins', 'all_severities', 'filters', 'errors_selected', 'build_details', 'commit_details', 'committer', 'commit_message', 'timing', 'created', 'started', 'finished', 'add_to_queue_failed', 'composer', 'php_loc', 'php_parallel_lint', 'email', 'atoum', 'campfire', 'clean_build', 'copy_build', 'deployer', 'env', 'grunt', 'hipchat_notify', 'irc', 'lint', 'mysql', 'package_build', 'pdepend', 'pgsql', 'phan', 'phar', 'phing', 'php_cs_fixer', 'shell', 'slack_notify', 'xmpp', 'security_checker', 'confirm_message', 'confirm_title', 'confirm_ok', 'confirm_cancel', 'confirm_success', 'confirm_failed', 'public_status_title', 'public_status_image',. 'public_status_page'

**Strings same than English:** 'reset_emailed', 'reset_enter_password', 'reset_new_password', 'reset_change_password', 'reset_no_user_exists', 'reset_email_body', 'reset_email_title', 'reset_invalid', 'login', 'toggle_navigation', 'n_builds_pending', 'n_builds_running', 'branch_x', 'dashboard', 'plugins', 'view', 'x_of_x_failed', 'last_successful_build', 'never_built_successfully', 'all_builds_passed', 'last_failed_build', 'never_failed_build', 'new_project', 'project_x_not_found', 'local', 'choose_github', 'error_hg', 'error_git', 'error_gitlab', 'error_github', 'error_bitbucket', 'error_path', 'all_branches', 'builds', 'date', 'project', 'commit', 'branch', 'status', 'prev_link', 'next_link', 'public_key', 'delete_build', 'webhooks', 'webhooks_help_github', 'build_x_not_found', 'committed_by_x', 'commit_id_x', 'chart_display', 'build', 'lines', 'comment_lines', 'noncomment_lines', 'lines_of_code', 'quality_trend', 'codeception_errors', 'php_mess_detector_warnings', 'php_code_sniffer_warnings', 'php_code_sniffer_errors', 'php_parallel_lint_errors', 'php_unit_errors', 'php_docblock_checker_warnings', 'issues', 'codeception_feature', 'codeception_suite', 'codeception_time', 'codeception_synopsis', 'file', 'line', 'class', 'method', 'message', 'start', 'end', 'from', 'to', 'result', 'ok', 'took_n_seconds', 'build_started', 'build_finished', 'test_message', 'test_no_message', 'test_success', 'test_fail', 'test_skipped', 'test_error', 'test_todo', 'test_total', 'password_change', 'save', 'update_your_details', 'your_details_updated', 'user_n_not_found', 'settings_saved', 'settings_check_perms', 'settings_cannot_write', 'settings_github_linked', 'settings_github_not_linked', 'build_settings', 'github_application', 'github_sign_in', 'github_where_to_find', 'github_where_help', 'email_settings', 'email_settings_help', 'application_id', 'application_secret', 'smtp_server', 'smtp_port', 'smtp_username', 'smtp_password', 'from_email_address', 'default_notification_address', 'use_smtp_encryption', 'none', 'failed_after', '5_mins', '15_mins', '30_mins', '1_hour', '3_hours', 'cannot_update_composer', 'x_has_been_removed', 'x_has_been_added', 'provided_by_package', 'suggested_packages', 'title', 'description', 'version, 'install', 'remove', 'search_packagist_for_more', 'search', 'build-summary', 'stage', 'duration', 'plugin', 'stage_setup', 'stage_test', 'stage_complete', 'stage_success', 'stage_failure', 'stage_broken', 'stage_fixed', 'update_app', 'updating_app', 'not_installed', 'install_instead', 'passing_build', 'failing_build', 'log_output', 'critical', 'high', 'normal', 'low'.

**Comment by flavioheleno** [comment]
Hi, I'm taking a shot at this.

**Comment by corpsee** [comment]
@flavioheleno Excellent! Thanks.
