### ISSUE TITLE
[Bug] Rebuild from build view runs into an error

### ISSUE THREAD

**Issue by kromonos** [php-censor/php-censor#372]
## Expected behavior

Should start a new build

## Actual behavior

Runs into a `Message: Column "user_id" must be an int.` error

## Steps to reproduce

Click onto `Build #123` and start a new rebuild with the rebuild buttons top right
![Screenshot at 2020-07-24 04-52-34](https://user-images.githubusercontent.com/1553902/88357140-c3dc4e80-cd59-11ea-8b5b-a8a050ce517e.png)
![Screenshot at 2020-07-24 04-52-47](https://user-images.githubusercontent.com/1553902/88357207-030a9f80-cd5a-11ea-8c54-47a6137304fe.png)
![Screenshot at 2020-07-24 04-52-52](https://user-images.githubusercontent.com/1553902/88357205-00a84580-cd5a-11ea-9d69-1291f86b8c43.png)

## Environment

PHP Censor version: 1.2.0
Operating System: Linux
PHP version: 7.3
MySQL version: 5.7

**Comment by corpsee** [comment]
@kromonos Thanks!

**Comment by corpsee** [comment]
@kromonos Fixed in branch `release-1.2` and will be released with patch `1.2.1`. Could you check the fix please?

**Comment by kromonos** [comment]
Seems to work now. Thank you 🙂
