### ISSUE TITLE
[Feature] Add environment settings for webhook build

### ISSUE THREAD

**Issue by gnomii** [php-censor/php-censor#407]
## Add environment settings for webhook build

When you configure a webhook parameters, there is no environment parameters. At the moment, the branch parameter will fetch the attached environments to run all build environments.

It would be great to integrate the environment parameters to run only build of the environment concerned.

**Comment by corpsee** [comment]
@gnomii Thanks.

I don't clear understand what exactly you want. GET parameter with environment variable in the webhook URL will solve your issue?

**Comment by gnomii** [comment]
Yes.

Actually I send a POST like "https://PHPCENSOR/webhook/git/PROJECT?branch=dev" and I would like to replace "branch" by "environment" and of course to build the environment.

**Comment by corpsee** [comment]
@gnomii Could you test branch `2.1-webhook-environment` for your case with environment param? GET parameter named "environment" (For example: *https://PHPCENSOR/webhook/git/PROJECT?environment=dev*).

**Comment by gnomii** [comment]
@corpsee I tested and it's work. Great !!! thank's you

**Comment by corpsee** [comment]
@gnomii Thanks! I merged the branch into `master`. The feature will be released with version `2.1.0`.
