### ISSUE TITLE
Socket error 0: 111

### ISSUE THREAD

**Issue by Ooypunk** [php-censor/php-censor#410]
When I run "bin/console php-censor:worker" on the command line, I get this error message:
"
In StreamSocket.php line 27:
                       
  Socket error 0: 111
"

What does that mean?

**Comment by corpsee** [comment]
You should install and start Beanstalkd queue.

**Comment by Ooypunk** [comment]
First, might I suggest then that the error messages says so?

Second, Beanstalkd is installed; when I type `beanstalkd -v` I get "beanstalkd 1.10".
You say "start the queue", but how do I do that? According to the manual this isn't necessary.

**Comment by corpsee** [comment]
The error says that you cann't connect to your Beanstalkd from application. You should check your queue configuration, installation etc.

Try to connect to your Beanstalkd from PHP-script (Not from PHP Censor). It is working fine?

Additionally, Could you give more details about your installation (PHP Censor version, PHP version, PHP Censor configuration etc.)?

**Comment by Ooypunk** [comment]
Sorry I didn't respond earlier. It was, as you said, that Beanstalkd wasn't running. I started it with "/etc/init.d/beanstalkd start", then this error was gone.

IMHO, this should be added to the manual.

**Comment by Ooypunk** [comment]
Sorry I didn't respond earlier. It was, as you said, that Beanstalkd wasn't running. I started it with "/etc/init.d/beanstalkd start", then this error was gone.

IMHO, this should be added to the manual.

**Comment by corpsee** [comment]
> Sorry I didn't respond earlier. It was, as you said, that Beanstalkd wasn't running. I started it with "/etc/init.d/beanstalkd start", then this error was gone.
> 
> IMHO, this should be added to the manual.

@Ooypunk Excellent! Could you create a PR for the manual with additions?

**Comment by Ooypunk** [comment]
I'll try!
