### ISSUE TITLE
Project too large or settings I have missed?

### ISSUE THREAD

**Issue by Ooypunk** [php-censor/php-censor#418]
There's this project I try to get tested, but two plugins give errors:
- "PHP Code Sniffer": "Allowed memory size [...] exhausted"
- "PHP Mess Detector": "The process [...] exceeded the timeout of 600 seconds."

Are there settings to get these to work? Like, for example, double the time-out time for a specific plugin?

**Comment by corpsee** [comment]
I guess your project is too big and wand more build time and memory.

1. You can increase allowed memory size in PHP settings.
2. You can increase queue timeout in application settings option `php-censor.queue.lifetime`.
