### ISSUE TITLE
[Bug] Can not use webhook with "environment"

### ISSUE THREAD

**Issue by gnomii** [php-censor/php-censor#432]
Hello,

I have two environments "development" and "production" to deploy my projects. I use a webhook with gitea server and I receive a 500 status code when it called the webhook.

I have this error since tag 2.1.0. Before this, I used a master with this feature https://github.com/php-censor/php-censor/issues/407

You can try with curl command in terminal: 

`curl 'PHPCENSOR/webhook/git/PROJECTID?environment=development'`

Returns: 
`
{"status":"failed","error":"PHPCensor\\Controller\\WebhookController::createBuild(): Argument #3 ($commitId) must be of type string, null given, called in \/usr\/local\/www\/php-censor\/src\/Controller\/WebhookController.php on line 368"}
`

**Comment by corpsee** [comment]
@gnomii Could you check fix in the branch `2.1-secrets-security`, please? Thanks!

**Comment by gnomii** [comment]
@corpsee I have this error now:

`
{"status":"failed","error":"Symfony\\Component\\HttpFoundation\\Response::setContent(): Argument #1 ($content) must be of type ?string, array given, called in \/usr\/local\/www\/php-censor\/src\/Controller\/WebhookController.php on line 91"}
`

**Comment by gnomii** [comment]
And I see I can use the identifier of project but the ID in the url of webhook, is it normal ?

**Comment by corpsee** [comment]
@gnomii
1. I fixed error with `setContent()`. Could you check again, please?
2. About `projectId`: I guess it is normal because ID is not a secret information. Also integrations with Github etc. have it own payload without project ID.

**Comment by gnomii** [comment]
@corpsee 

Ok, thanks you very much for your reactivity.

I try with curl command to execute the webhooks but for one case I have status OK, and other case a status ignored with this message `"message":"For this commit already created builds (140)"`.

In the two case, I don't commit anything before execute curl command.

**Comment by corpsee** [comment]
@gnomii As far as I understand, you don't have parameter `commit_id` in webhook and you build `HEAD`. And you built 2 builds on the same commit.

**Comment by gnomii** [comment]
@corpsee yes, I don't have `commit_id`.

In the case of project X, I can execute the webhook many times, but for the project Y case, the webhook returns the error.
If I directly execute the build on the interface, I have not error.

I test with a new commit on project Y, and the webhook give me the same errors. Perhaps I have a problem with my repo ?

I will try with other projects.

**Comment by gnomii** [comment]
I delete old builds and it works. I think it's in my side, I migrate the database from an other server, it's not a clean installation.

Thanks you for your help !

**Comment by corpsee** [comment]
@gnomii Now you can use branch `release-2.1` or tag `2.1.2`.
