### ISSUE TITLE
Survey: Cron-worker removing

### ISSUE THREAD

**Issue by corpsee** [php-censor/php-censor#77]
@vinpel, @ket4yii, @valeriitropin, @JoolsMcFly, @ss-gxp, @bochkovprivate, @StudioMaX, Does anyone use a cron-worker? What do you think about removing it from PHP Censor in the near future?
I think that it is enough to leave only a worker (daemon), so that it would be easier to support the project.

**Comment by StudioMaX** [comment]
Personally I don't use a cron-worker. Perhaps it is needed by those who don't have root-access to the server and cannot install Supervisor and Beanstalkd.

**Comment by ket4yii** [comment]
I think that cron worker is useless thing. You can't scale it, it works strange, it's hard to maintain and it's not real daemon. So, I think nobody is going to cry if you remove it(maybe I'm not right) :)

**Comment by ss-gxp** [comment]
I use (no choice).
I think whatever the build was started (command line, crontab or any queue), this should not be important.
If it is difficult to maintain, may be then need to refactor the launch process in separate classes that can receive callbacks at certain points to do their work (like release job or something other).

**Comment by bochkovprivate** [comment]
Personally I don't use a cron-worker.

I did not like it because on my setup it often caused numerous instances of worker for slow-running builds. As I was not able to limit the number of workers (unlike to supervisor-based setup) the build-server became stale and builds last for hours.

**Comment by corpsee** [comment]
@StudioMaX, @ket4yii, @ss-gxp, @bochkovprivate Thank you for the answers!
@ss-gxp Can you explaine why you don't have a choice (Supervisor, Beanstalkd or another reason)?

**Comment by vinpel** [comment]
i don't use cron worker too

**Comment by ss-gxp** [comment]
> Can you explaine why you don't have a choice (Supervisor, Beanstalkd or another reason)?
In short: I can not do it - no root rights.

**Comment by corpsee** [comment]
@ss-gxp OK, Thanks. I will not remove cron-worker yet.

**Comment by ket4yii** [comment]
@ss-gxp why do you need root rights for daemon?

**Comment by ss-gxp** [comment]
> why do you need root rights for daemon?

Any suggestions?
(install into home, I do not think it's right)

**Comment by ket4yii** [comment]
@ss-gxp you don't need root rights to daemonise phpcensor. If there are some restriction and you are not allowed to use systemd and supervisord, you can use *nohup*. And beanstalk can run without root rights, too.

**Comment by SimonHeimberg** [comment]
I like the possibility to run `bin/console php-censor:run-builds` manually for doing some debugging. It does not need beanstalk installed nor properly configured.

**Comment by corpsee** [comment]
Ok, useful case. Thank you for the answer, @SimonHeimberg.
