### ISSUE TITLE
[Feature] Remember me

### ISSUE THREAD

**Issue by funivan** [php-censor/php-censor#81]
Hello. Thank you for the great project.

Is there any way to make checkbox `remember me` in the login page?

**Comment by corpsee** [comment]
Hi, @funivan. Thanks! Yes, I already think about it but didn't have time yet.

**Comment by corpsee** [comment]
Done. @funivan Can you test this feature in `feature-remember-me` branch?

**Comment by corpsee** [comment]
Now in `master` branch.

**Comment by funivan** [comment]
@corpsee thanks
