### ISSUE TITLE
[Feature] build results better navigatable

### ISSUE THREAD

**Issue by SimonHeimberg** [php-censor/php-censor#85]
I propose
 * links from Summary (in Information tag) to the related (1st) Error (in Error tab).
 * filtering on Error tab for columns `Severity`, `Plugin` and maybe `File`.
 * Maybe pagination for Error tab? At my first try, I had 19550 errors, which blocks the error tab for some time.

**Comment by corpsee** [comment]
All of this make sense (I already plan filtering and pagination for errors but didn't have time for this). Thank you for your request @SimonHeimberg!

**Comment by corpsee** [comment]
#123

**Comment by corpsee** [comment]
Pagination for build errors done. Branch `feature-pagination-for-errors`.

**Comment by corpsee** [comment]
Filtration for errors by severity and plugin done. Same branch.

**Comment by corpsee** [comment]
Links from summary to errors done. Same branch.

**Comment by corpsee** [comment]
In the `master` branch now.
