### ISSUE TITLE
[feature] allow to show coverage crated by phpunit

### ISSUE THREAD

**Issue by SimonHeimberg** [php-censor/php-censor#86]
This can probably be done easily with some webserver config, but some hints in the doc would be welcome.
And including the link somewhere in the build would be great.

**Comment by corpsee** [comment]
It is useful feature. Thanks!

**Comment by SimonHeimberg** [comment]
current possibility:
```yml
    "php_unit":
        coverage: ../../../public/coverage-phpunit/build%BUILD%/
```
Then the coverage is visible on `http:yourhost.example.com/php-censor/coverage-phpunit/build27`. Be careful, there is no login required. And you must remove old coverage results yourself if desired.

**Comment by SimonHeimberg** [comment]
To see the total result somewhere would be nice too. In the log, maybe even in the graph?
(Find it in topmost index.html, in <tr> containing `>Total</td>` : `grep -A15 '>Total</td>' coverage/path/index.html | grep --max-count=1 '% covered'`)

**Comment by SimonHeimberg** [comment]
much simpler than parsing index.html: `--coverage-text`, writes to output or to a file.

**Comment by corpsee** [comment]
@SimonHeimberg Fixed in branch `improve-pdepend`. It works like Pdepend plugin, link to coverage in the build log. Can you check it please?

**Comment by corpsee** [comment]
Merged into `master`. Feel free to reopen and comment.

**Comment by SimonHeimberg** [comment]
The printed url works for showing the report. Confirm this issue as closed.

Showing the summary (with `phpunit ... --coverage-text reportFile.txt ...` and then `grep --max-count 3 '% ' reportFile.txt` [1])
or even including this 3 values [1] in the graph would still be great.

[1] The 1st 3 values (with %) are the total coverage of Classes, Methods and Lines.

**Comment by corpsee** [comment]
@SimonHeimberg Thank you for the testing and notes!

1. Yes, I guess it should be a new issue. Can you create issue for it please? Thanks.
2. About coverage without login I commented in #107.
