### ISSUE TITLE
check yaml input submitted from project/edit page

### ISSUE THREAD

**Issue by SimonHeimberg** [php-censor/php-censor#95]
Do some yaml validation on the project configuration submitted by the project/edit page.

Suggestions:
 * check valid yaml for project config (is currently silently accepted)
 * check valid yaml for env (currently shows the error page)
 * configure the text areas that tabs are converted to 4 spaces
 * maybe do some more checking (valid attributes?, valid plugins?)

Reason:
When I enter my project config, I often create invalid yaml code. Most time it is a tab instead of spaces, or wrong number of spaces.

**Comment by corpsee** [comment]
Good idea! Thanks @SimonHeimberg!
